.\" 
.TH "eduactiv8" "6" "3.70.913" "" "Games"
.SH "NAME"
eduactiv8 \-  Educational Activities for Kids
.SH "SYNOPSIS"
.B eduactiv8
.SH "DESCRIPTION"
eduActiv8 is a set of educational activities and games for children aged between 3 and 10. The activities are grid based and can be played all in a single window. eduActiv8 includes maths, reading, writing, painting, and memory activities.

.SH "FEATURES"
.TP
- Letter flashcards, jumbled abc, word mazes, sort letters
.TP
- Learn to write (best used with touchscreens or drawing tablets)
.TP
- Maths: count, basic operations, sort numbers, fractions, shapes
.TP
- Learn colour names
.TP
- Short term memory training activities
.TP
- Mazes and puzzles

.SH "REQUIREMENTS"
.TP
- python 2.7+
.TP
- python-pygame
.TP
- espeak

.SH "USAGE"

The game will start by default in windowed mode, but it can be changed into a fullscreen mode. The configuration will be maintained whenever it is started again later.

The screen will present a set of icons on the left, each of them representing a set of activities, and a working canvas to the right. When an icon is selected, a second list of icons will be represented, each of them being a different activity to play with.

You can select the language in the setup menu, and it will also be maintained among different executions of the game.

.SH "FILES"
The game data for each user is stored at ~/.local/share/eduactiv8/
.SH "SEE ALSO"
You can find more information at http://sourceforge.net/projects/eduactiv8/
