.\" 
.TH "eduactiv8" "6" "3.80.130" "" "Games"
.SH "NAME"
eduactiv8 \-  Educational Activities for Kids
.SH "SYNOPSIS"
.B eduactiv8
.SH "DESCRIPTION"
eduActiv8 is a set of educational activities and games for children aged between 3 and 10. The activities are grid based and can be played all in a single window. eduActiv8 includes maths, reading, writing, painting, and memory activities.

.SH "FEATURES"
.TP
- Letter flashcards, jumbled abc, word mazes, sort letters
.TP
- Learn to write (best used with touchscreens or drawing tablets)
.TP
- Maths: count, basic operations, sort numbers, fractions, shapes, patterns
.TP
- Learn colour names
.TP
- Short term memory training activities
.TP
- Mazes and puzzles

.SH "REQUIREMENTS"
.TP
- python 2.7+
.TP
- python-pygame
.TP
- espeak

.SH "USAGE"

The game will start by default in windowed mode, but it can be changed into a fullscreen mode. The configuration will be maintained whenever it is started again later.

The screen will present a menu consisting of two columns of icons on the left, and a working canvas to the right. The left column of the menu displays expandable groups of categories. When a category is selected a list of available activities will be shown in the right column. Upon clicking on an activity icon it will start to the right of the menu.

There are two steps to selecting a language. The language selected on the start screen will change the language of the initial screen only, but also will be used as a default language for new users. After logging in individual users can choose a different language (in the language activity) that will be saved for them. This allows users to use the program to learn other language than their own.

.SH "FILES"
The game data for each user is stored at ~/.local/share/eduactiv8/
.SH "SEE ALSO"
You can find more information at https://www.eduactiv8.org
