# -*- coding: utf-8 -*-

d = dict()
d["a4a_animals"] = ['vaca', 'gall dindi', 'gamba', 'llop', 'pantera', 'ós panda', 'garsa', 'cloïssa', 'poni', 'ratolí', 'carlí', 'coala', 'granota', 'marieta', 'goril·la', '<llama>', 'voltor', '<hamster>', 'ocell', 'estrella de mar', 'corb', 'periquito', 'eruga', 'tigre', 'colibrí', 'piranya', 'porc', 'escorpí', 'guineu', 'lleopard', 'iguana', 'dofí', 'ratpenat', 'pollet', 'cranc', 'gallina', 'vespa', 'camaleó', 'balena', 'eriçó', 'cervatell', 'ant', 'abella', 'escurçó', '<shrike>', '<donkey>', '<guinea pig>', 'peresós', 'cavall', '<penguin>', 'llúdriga', 'ós', 'zebra', 'estruç', 'camell', 'antílop', 'lèmur', 'tórtora', 'llama', 'talp', '<ray>', '<ram>', 'mofeta', 'medusa', 'ovella', 'tauró', 'gatet', 'cérvol', 'cargol', 'flamenc', 'conill', 'ostra', 'castor', 'pardal', 'colom', 'àguila', 'escarabat', 'hipopòtam', 'òliba', 'cobra', 'salamandra', 'oca', 'cangur', 'libèl·lula', 'gripau', 'pelicà', 'calamar', '<lion cub>', 'jaguar', 'ànec', 'llangardaix', 'rinoceront', 'hiena', 'bou', 'paó', 'lloro', 'uapití', 'caiman', 'formiga', 'cabra', '<baby rabbit>', 'lleó', 'esquirol', 'opòssum', 'ximpanzé', 'cérvola', '<gopher>', '<elephant>', 'girafa', 'aranya', 'cadell', 'gaig', '<seal>', '<rooster>', 'tortuga', 'toro', 'gat', 'rata', 'llimac', 'búfal', 'merla', 'cigne', 'llagosta', 'gos', 'mosquit', 'serp', 'pollastre', 'ós formiguer']
d["a4a_sport"] = ['judo', 'piscina', 'ciclista', 'estirar', 'casc', '<ice skating>', 'caminar', 'córrer', 'nedar', 'saltar', 'caminar', '<boxing>', 'hoquei', 'cursa', 'llançar', 'patinar', 'guanyar', 'ajupir', 'esquiar', 'golf', '<whistle>', 'torxa', '<sailing>', 'dret', 'tennis', 'saltar', 'rem', 'fúting', 'corda']
d["a4a_body"] = ['dentadura', 'galta', 'turmell', 'genoll', 'dit del peu', 'múscul', 'boca', '<feet>', 'mà', 'colze', 'cabell', 'pestanya', 'barba', '<belly button>', 'polze', 'pit', 'nariu', 'nas', 'maluc', 'braç', '<eyebrow>', 'puny', 'coll', 'canell', 'gola', '<eye>', 'cama', 'espina', 'orella', 'dit', 'peu', 'trena', 'cara', 'esquena', 'barbeta', 'natges', 'cuixa', 'panxa']
d["a4a_people"] = ['noia', '<male>', 'fill', '<mates>', '<friends>', '<baby>', 'nen', 'pare', 'mama', '<twin boys>', '<brothers>', 'home', 'mare', '<grandfather>', 'família', '<female>', 'muller', 'marit', 'núvia', '<madam>', 'àvia', 'parella', 'mosso', '<twin girls>', 'tribu', 'noi', '<sisters>', 'dona', 'dama']
d["a4a_food"] = ['caramel', 'salsitxa', 'hamburguesa', '<steak>', 'dolç de xocolata', 'bunyol', 'coco', 'arròs', '<ice cream>', 'gelatina', '<yoghurt>', 'postre', '<pretzel>', '<peanut>', 'melmelada', 'banquet', 'galeta', '<bacon>', 'espècia', 'cafè', 'pastís', 'llimonada', 'xocolata', '<water bottle>', 'dinar', 'glaçó', 'sucre', 'salsa', 'sopa', 'suc', 'patata fregida', 'pastís', '<mashed potatoes>', '<tea>', 'brioix', 'formatge', '<beef>', 'sandvitx', '<slice>', 'espurnes', 'pizza', 'farina', 'xiclet', 'espagueti', 'rostit', 'guisat', 'untar', 'carn', 'llet', 'àpat', 'blat de moro', 'pa', 'nou', 'ou', '<hot dog>', 'pernil']
d["a4a_clothes_n_accessories"] = ['<jewellery>', 'mitjó', 'jaqueta', 'taló', 'bata', '<shorts>', 'butxaca', 'collaret', 'dessuadora', 'uniforme', 'impermeable', '<trousers>', '<sunglasses>', 'abric', 'jersei', 'camisa', 'sandàlia', 'mudada', '<pyjamas>', 'faldilla', '<zip>', '<shoes>', 'joia', '<tie>', 'sabatilla', '<gloves>', 'barret', 'màniga', 'gorra', '<swimming suit>', '<trainer>', 'armilla', 'ulleres', 'cordó', 'pedaç', 'bufanda', 'sabata', 'botó', 'vestit', 'faixa', '<shoe sole>', 'mantell', 'pantalons', 'quimono', '<overalls>']
d["a4a_actions"] = ['llepar', 'esmaixada', 'demanar', '<fell>', 'esgarrapar', 'tocar', 'ensumar', 'mirar', 'escalada', 'cavar', 'udolar', 'dormir', 'explorar', 'dibuixar', 'abraçar', 'ensenyar', 'migdiada', 'argila', 'pescar', 'picar de mans', 'plorar', 'cantar', 'trobar-se', '<sell>', 'picotejar', 'batre', 'agenollar', 'trobar', 'ballar', 'tossir', 'tallar', 'pensar', 'bordar', 'parlar', 'animar', '<bake>', 'escriure', '<punch>', '<strum>', 'estudiar', 'llaurar', 'somiar', 'bústia', 'immersió', 'xiuxiuejar', 'sanglotar', 'sacsejar', 'donar de menjar', 'gatejar', 'acampar', 'vessar', 'rentar', 'cridar', 'esquinçar', 'flotar', 'estirar', '<ate>', 'petó', 'seure', "sortir de l'ou", "picada d'ullet", 'sentir', 'bessar', 'jugar', 'banyar', 'parlar', 'conduir', 'beguda', 'volar', '<juggle>', 'mica', '<sweep>', 'mirar-se', 'teixir', 'aixecar', 'informar', 'llegir', 'raucar', 'mirar fixament', 'menjar']
d["a4a_construction"] = ['far', 'porta', 'circ', '<church>', '<kennel>', 'temple', 'fum', 'xemeneia', 'maó', '<well>', 'carrer', 'castell', 'botiga', 'escala', 'escola', 'granja', 'pont', 'presa', 'piràmide', 'graner', 'molí', 'finestra', 'cabana', 'esglaó', 'botiga', 'cobert', 'teulada', 'campanar', 'garatge', 'mesquita', 'hospital', 'tenda', 'casa', 'mur', 'banc', 'finestró', 'cabana']
d["a4a_nature"] = ['terreny', 'penya-segat', 'turó', 'canó', 'roca', 'mar', 'llac', 'costa', 'riba', 'muntanya', 'estany', 'pic', 'lava', 'cova', 'duna', 'illa', 'bosc', 'desert', 'iceberg']
d["a4a_jobs"] = ['pallasso', 'enginyer', 'sacerdot', 'veterinari', 'jutge', 'cuiner', 'atleta', 'bibliotecària', 'malabarista', '<policeman>', 'fontaner', 'insígnia', 'reina', 'granger', '<magician>', 'cavaller', 'metge', 'paleta', '<cleaner>', 'professora', 'caçador', 'soldat', 'músic', 'advocat', 'pescador', 'princesa', 'bomber', 'monja', 'pirata', 'vaquer', 'electricista', 'infermera', 'rei', 'president', '<office worker>', 'fuster', 'joquei', 'treballador', 'mecànic', 'pilot', 'actor', 'cuinar', 'estudiant', 'carnisser', 'comptable', 'princep', 'papa', 'mariner', 'boxejador', '<ballet dancer>', 'entrenador', 'astronauta', '<painter>', '<anaesthesiologist>', '<scientist>']
d["a4a_fruit_n_veg"] = ['pastanaga', '<blackberries>', 'api', 'nap', 'cacau', 'préssec', 'meló', 'pomelo', 'bròquil', '<grapes>', 'espinac', 'figa', 'nucli', 'rave', '<tomato>', 'kiwi', 'espàrrec', '<olives>', '<cucumbers>', '<beans>', 'maduixa', 'pebrot', 'gerd', 'albercoc', '<potatoes>', '<peas>', 'col', '<cherries>', 'carbassó', '<blueberries>', 'pera', 'taronja', 'carbassa', 'alvocat', 'all', 'ceba', 'poma', 'llima', 'coliflor', 'mango', 'enciam', 'llimona', '<aubergine>', '<artichokes>', '<plums>', 'porro', '<bananas>', 'papaia']
d["a4a_transport"] = ['veler', 'taxi', 'cotxe', 'bicicleta', 'barca solera', 'pedal', 'autobús', 'manillar', 'barca', 'camió', 'trineu', 'catifa', 'moto', 'tren', 'vaixell', 'furgoneta', 'canoa', 'coet', 'màstil', '<sledge>', '<bicycle>']