# -*- coding: utf-8 -*-

d = dict()


d["a4a_animals"] = ['vaca', 'gall dindi', 'gamba', 'llop', 'pantera', 'ós panda', 'garsa', 'cloïssa', 'poni', 'ratolí', 'carlí', 'coala', 'granota', 'marieta', 'goril·la', 'llama', 'voltor', 'hàmster', 'ocell', 'estrella de mar', 'corb', 'periquito', 'eruga', 'tigre', 'colibrí', 'piranya', 'porc', 'escorpí', 'guineu', 'lleopard', 'iguana', 'dofí', 'ratpenat', 'pollet', 'cranc', 'gallina', 'vespa', 'camaleó', 'balena', 'eriçó', 'cervatell', 'ant', 'abella', 'escurçó', 'botxí', 'ase', "conillet d'Índies", 'peresós', 'cavall', 'pingüí', 'llúdriga', 'ós', 'zebra', 'estruç', 'camell', 'antílop', 'lèmur', 'tórtora', 'llama', 'talp', 'ralla', 'moltó', 'mofeta', 'medusa', 'ovella', 'tauró', 'gatet', 'cérvol', 'cargol', 'flamenc', 'conill', 'ostra', 'castor', 'pardal', 'colom', 'àguila', 'escarabat', 'hipopòtam', 'òliba', 'cobra', 'salamandra', 'oca', 'cangur', 'libèl·lula', 'gripau', 'pelicà', 'calamar', 'cadell de lleó', 'jaguar', 'ànec', 'llangardaix', 'rinoceront', 'hiena', 'bou', 'paó', 'lloro', 'uapití', 'caiman', 'formiga', 'cabra', 'llebrató', 'lleó', 'esquirol', 'opòssum', 'ximpanzé', 'cérvola', 'esquirol terrestre', 'elefant', 'girafa', 'aranya', 'cadell', 'gaig', 'foca', 'gall', 'tortuga', 'toro', 'gat', 'rata', 'llimac', 'búfal', 'merla', 'cigne', 'llagosta', 'gos', 'mosquit', 'serp', 'pollastre', 'ós formiguer']
d["a4a_sport"] = ['judo', 'piscina', 'ciclista', 'estirar', 'casc', 'patinatge sobre gel', 'caminar', 'córrer', 'nedar', 'saltar', 'caminar', 'boxa', 'hoquei', 'cursa', 'llançar', 'patinar', 'guanyar', 'ajupir', 'esquiar', 'golf', 'xiulet', 'torxa', 'navegació', 'dret', 'tennis', 'saltar', 'rem', 'fúting', 'corda']
d["a4a_body"] = ['dentadura', 'galta', 'turmell', 'genoll', 'dit del peu', 'múscul', 'boca', 'peus', 'mà', 'colze', 'cabell', 'pestanya', 'barba', 'melic', 'polze', 'pit', 'nariu', 'nas', 'maluc', 'braç', 'cella', 'puny', 'coll', 'canell', 'gola', 'ull', 'cama', 'espina', 'orella', 'dit', 'peu', 'trena', 'cara', 'esquena', 'barbeta', 'natges', 'cuixa', 'panxa']
d["a4a_people"] = ['noia', 'home', 'fill', 'companys', 'amics', 'nadó', 'nen', 'pare', 'mama', 'bessons', 'germans', 'home', 'mare', 'avi', 'família', 'dona', 'muller', 'marit', 'núvia', 'senyora', 'àvia', 'parella', 'mosso', 'bessones', 'tribu', 'noi', 'germanes', 'dona', 'dama']
d["a4a_food"] = ['caramel', 'salsitxa', 'hamburguesa', 'bistec', 'dolç de xocolata', 'bunyol', 'coco', 'arròs', 'gelat', 'gelatina', 'iogurt', 'postre', 'bretzel', 'cacauet', 'melmelada', 'banquet', 'galeta', 'cansalada', 'espècia', 'cafè', 'pastís', 'llimonada', 'xocolata', "ampolla d'aigua", 'dinar', 'glaçó', 'sucre', 'salsa', 'sopa', 'suc', 'patata fregida', 'pastís', 'puré de patates', 'te', 'brioix', 'formatge', 'vedella', 'sandvitx', 'tros', 'espurnes', 'pizza', 'farina', 'xiclet', 'espagueti', 'rostit', 'guisat', 'untar', 'carn', 'llet', 'àpat', 'blat de moro', 'pa', 'nou', 'ou', 'frankfurt', 'pernil']
d["a4a_clothes_n_accessories"] = ['joieria', 'mitjó', 'jaqueta', 'taló', 'bata', 'pantalons curts', 'butxaca', 'collaret', 'dessuadora', 'uniforme', 'impermeable', 'pantalons', 'ulleres de sol', 'abric', 'jersei', 'camisa', 'sandàlia', 'mudada', 'pijama', 'faldilla', 'cremallera', 'sabates', 'joia', 'corbata', 'sabatilla', 'guants', 'barret', 'màniga', 'gorra', 'banyador', 'entrenador', 'armilla', 'ulleres', 'cordó', 'pedaç', 'bufanda', 'sabata', 'botó', 'vestit', 'faixa', 'sola de la sabata', 'mantell', 'pantalons', 'quimono', 'maca']
d["a4a_actions"] = ['llepar', 'esmaixada', 'demanar', 'va caure', 'esgarrapar', 'tocar', 'ensumar', 'mirar', 'escalada', 'cavar', 'udolar', 'dormir', 'explorar', 'dibuixar', 'abraçar', 'ensenyar', 'migdiada', 'argila', 'pescar', 'picar de mans', 'plorar', 'cantar', 'trobar-se', 'vendre', 'picotejar', 'batre', 'agenollar', 'trobar', 'ballar', 'tossir', 'tallar', 'pensar', 'bordar', 'parlar', 'animar', 'enfornar', 'escriure', 'cop de puny', 'rasguejar', 'estudiar', 'llaurar', 'somiar', 'bústia', 'immersió', 'xiuxiuejar', 'sanglotar', 'sacsejar', 'donar de menjar', 'gatejar', 'acampar', 'vessar', 'rentar', 'cridar', 'esquinçar', 'flotar', 'estirar', 'va menjar', 'petó', 'seure', "sortir de l'ou", "picada d'ullet", 'sentir', 'bessar', 'jugar', 'banyar', 'parlar', 'conduir', 'beguda', 'volar', 'malabars', 'mica', 'escombrar', 'mirar-se', 'teixir', 'aixecar', 'informar', 'llegir', 'raucar', 'mirar fixament', 'menjar']
d["a4a_construction"] = ['far', 'porta', 'circ', 'església', 'gossera', 'temple', 'fum', 'xemeneia', 'maó', 'pou', 'carrer', 'castell', 'botiga', 'escala', 'escola', 'granja', 'pont', 'presa', 'piràmide', 'graner', 'molí', 'finestra', 'cabana', 'esglaó', 'botiga', 'cobert', 'teulada', 'campanar', 'garatge', 'mesquita', 'hospital', 'tenda', 'casa', 'mur', 'banc', 'finestró', 'cabana']
d["a4a_nature"] = ['terreny', 'penya-segat', 'turó', 'canó', 'roca', 'mar', 'llac', 'costa', 'riba', 'muntanya', 'estany', 'pic', 'lava', 'cova', 'duna', 'illa', 'bosc', 'desert', 'iceberg']
d["a4a_jobs"] = ['pallasso', 'enginyer', 'sacerdot', 'veterinari', 'jutge', 'cuiner', 'atleta', 'bibliotecària', 'malabarista', 'policia', 'fontaner', 'insígnia', 'reina', 'granger', 'mag', 'cavaller', 'metge', 'paleta', 'neteja', 'professora', 'caçador', 'soldat', 'músic', 'advocat', 'pescador', 'princesa', 'bomber', 'monja', 'pirata', 'vaquer', 'electricista', 'infermera', 'rei', 'president', "empleat d'oficina", 'fuster', 'joquei', 'treballador', 'mecànic', 'pilot', 'actor', 'cuinar', 'estudiant', 'carnisser', 'comptable', 'princep', 'papa', 'mariner', 'boxejador', 'ballarí de ballet', 'entrenador', 'astronauta', 'pintor', 'anestesiòleg', 'científic']
d["a4a_fruit_n_veg"] = ['pastanaga', 'mores', 'api', 'nap', 'cacau', 'préssec', 'meló', 'pomelo', 'bròquil', 'raïm', 'espinac', 'figa', 'nucli', 'rave', 'tomàquet', 'kiwi', 'espàrrec', 'olives', 'cogombres', 'mongetes', 'maduixa', 'pebrot', 'gerd', 'albercoc', 'patates', 'pèsols', 'col', 'cireres', 'carbassó', 'nabius', 'pera', 'taronja', 'carbassa', 'alvocat', 'all', 'ceba', 'poma', 'llima', 'coliflor', 'mango', 'enciam', 'llimona', 'albergínia', 'carxofes', 'prunes', 'porro', 'plàtans', 'papaia']
d["a4a_transport"] = ['veler', 'taxi', 'cotxe', 'bicicleta', 'barca solera', 'pedal', 'autobús', 'manillar', 'barca', 'camió', 'trineu', 'catifa', 'moto', 'tren', 'vaixell', 'furgoneta', 'canoa', 'coet', 'màstil', 'trineu', 'bicicleta']