# -*- coding: utf-8 -*-

d = dict()
d["a4a_animals"] = ['Kuh', 'Truthahn', 'Schrimps', 'Wolf', 'Panther', 'Panda', 'Elster', 'Muschel', 'Pony', 'Maus', 'Mops', 'Koala', 'Frosch', 'Marienkäfer', 'Gorilla', 'Lama', 'Geier', 'Hamster', 'Vogel', 'Seestern', 'Krähe', 'Sittich', 'Raupe', 'Tiger', 'Kolibri', 'Piranha', 'Schwein', 'Skorpion', 'Fuchs', 'Leopard', 'Leguan', 'Delfin', 'Fledermaus', 'Huhn', 'Krabbe', 'Henne', 'Wespe', 'Chameleon', 'Wal', 'Igel', 'Rehkitz', 'Elch', 'Biene', 'Viper', 'Würger', 'Esel', 'Guinea Schwein', 'Faultier', 'Pferd', 'Pinguin', 'Otter', 'Bär', 'Zebra', 'Strauß', 'Kamel', 'Antilope', 'Lemur', 'Taube', 'Lama', 'Maulwurf', 'Rochen', 'Widder', 'Stinktier', 'Qualle', 'Schaf', 'Hai', 'Kätzchen', 'Hirsch', 'Schnecke', 'Flamingo', 'Hase', 'Muschel', 'Biber', 'Spatz', 'Taube', 'Adler', 'Käfer', 'Nilpferd', 'Eule', 'Kobra', 'Salamander', 'Gans', 'Kängeruh', 'Libelle', 'Kröte', 'Pelikan', 'Tintenfisch', 'Löwenbaby', 'Jaguar', 'Ente', 'Eidechse', 'Rhinozeros', 'Hyäne', 'Ochse', 'Pfau', 'Papagei', 'Elch', 'Alligator', 'Ameise', 'Ziege', 'Baby Hase', 'Löwe', 'Eichhörnchen', 'Opossum', 'Schimpanse', 'Reh', 'Erdhörnchen', 'Elefant', 'Giraffe', 'Spinne', 'Hundewelpe', 'Tölpel', 'Seelöwe', 'Hahn', 'Schildkröte', 'Bulle', 'Katze', 'Ratte', 'Schnecke', 'Büffel', 'Amsel', 'Schwan', 'Hummer', 'Hund', 'Moskito', 'Schlange', 'Hühnchen', 'Ameisenbär']
d["a4a_sport"] = ['Judo', 'Billard', 'Reiten', 'Dehnen', 'Helm', 'Schlittschuh Laufen', 'Gehen', 'Laufen', 'Schwimmen', 'Springen', 'Wandern', 'Boxen', 'Hockey', 'Rennen', 'Werfen', 'Skaten', 'Gewinnen', 'Kniebeuge', 'Skifahren', 'Golf', 'Pfeife', 'Fackel', 'Segeln', 'Stehen', 'Tennis', 'Hochsprung', 'Rudern', 'Joggen', 'Seilspringen']
d["a4a_body"] = ['Zähne', 'Backe', 'Knöchel', 'Knie', 'Zeh', 'Muskel', 'Mund', 'Fuß', 'Hand', 'Ellbogen', 'Haar', 'Wimper', 'Bart', 'Bauchnabel', 'Daumen', 'Brust', 'Nasenloch', 'Nase', 'Hüfte', 'Arm', 'Augenbraue', 'Faust', 'Nacken', 'Handgelenk', 'Hals', 'Auge', 'Bein', 'Wirbelsäule', 'Ohr', 'Finger', 'Fuß', 'Zopf', 'Gesicht', 'Rücken', 'Kinn', 'Po', 'Oberschenkel', 'Bauch']
d["a4a_people"] = ['Mädchen', 'männlich', 'Sohn', 'Kumpel', 'Freunde', 'Baby', 'Kind', 'Vater', 'Mutter', 'Zwillinge', 'Brüder', 'Mann', 'Mutter', 'Großvater', 'Familie', 'weiblich', 'Ehefrau', 'Ehemann', 'Braut', 'Madame', 'Großmutter', 'Zusammen', 'Kerl', 'Zwillinge', 'Stamm', 'Junge', 'Schwestern', 'Frau', 'Lady']
d["a4a_food"] = ['Süßigkeiten', 'Wurst', 'Hamburger', 'Steak', 'Fondant', 'Doughnut', 'Kokosnuss', 'Reis', 'Eiscreme', 'Gelee', 'Joghurt', 'Nachtisch', 'Brezel', 'Erdnuss', 'Marmelade', 'Festmahl', 'Keks', 'Speck', 'Gewürz', 'Kaffee', 'Torte', 'Limonade', 'Schokolade', 'Wasserflasche', 'Mittagessen', 'Eis', 'Zucker', 'Soße', 'Suppe', 'Saft', 'Fritten', 'Kuchen', 'Stampfkartoffeln', 'Tee', 'Brötchen', 'Käse', 'Rindfleisch', 'Sandwich', 'Brotscheibe', 'Spritzgebäck', 'Pizza', 'Mehl', 'Kaugummi', 'Spaghetti', 'Braten', 'Eintopf', 'Aufstrich', 'Fleisch', 'Milch', 'Mahlzeit', 'Mais', 'Brot', 'Walnuss', 'Ei', 'Hot Dog', 'Schinken']
d["a4a_clothes_n_accessories"] = ['Schmuck', 'Socken', 'Jacket', 'Hacke', 'Kittel', 'Shorts', 'Tasche', 'Halskette', 'Sweatshirt', 'Uniform', 'Regenjacke', 'Hose', 'Sonnenbrille', 'Jacke', 'Pullover', 'Shirt', 'Sandalen', 'Anzug', 'Pyjama', 'Rock', 'Reißverschluss', 'Schuhe', 'Juwel', 'Krawatte', 'Pantoffel', 'Handschuhe', 'Hut', 'Ärmel', 'Kappe', 'Badeanzug', 'Trainingsanzug', 'Weste', 'Brille', 'Schnürsenkel', 'Flicken', 'Halstuch', 'Schuh', 'Knopf', 'Dress', 'Schärpe', 'Schuhsohle', 'Robe', 'Hose', 'Kimono', 'Overall']
d["a4a_actions"] = ['lecken', 'zuschlagen', 'betteln', 'fallen', 'kratzen', 'berühren', 'schnüffeln', 'sehen', 'klettern', 'graben', 'heulen', 'schlafen', 'erkunden', 'zeichnen', 'umarmen', 'lehren', 'ausruhen', 'kneten', 'fangen', 'klatschen', 'weinen', 'singen', 'treffen', 'verkaufen', 'picken', 'schlagen', 'knien', 'finden', 'tanzen', 'husten', 'schneiden', 'denken', 'bellen', 'sprechen', 'applaudieren', 'backen', 'schreiben', 'hauen', 'klimpern', 'studieren', 'pflügen', 'träumen', 'abschicken', 'tauchen', 'flüstern', 'schluchzen', 'schütteln', 'füttern', 'kriechen', 'zelten', 'kleckern', 'reinigen', 'schreien', 'reißen', 'fließen', 'ziehen', 'aß', 'küssen', 'sitzen', 'ausbrüten', 'blinken', 'hören', 'schmusen', 'spielen', 'waschen', 'plaudern', 'fahren', 'trinken', 'fliegen', 'jonglieren', 'beißen', 'fegen', 'schauen', 'stricken', 'heben', 'fangen', 'lesen', 'krächzen', 'starren', 'essen']
d["a4a_construction"] = ['Leuchtturm', 'Tür', 'Zirkus', 'Kirche', 'kennel', 'Tempel', 'Rauch', 'Schornstein', 'Ziegel', 'Brunnen', 'Straße', 'Burg', 'Speicher', 'Treppenhaus', 'Schule', 'Farm', 'Brücke', 'Damm', 'Pyramide', 'Scheune', 'Windmühle', 'Fenster', 'Hütte', 'Stufe', 'Laden', 'Schuppen', 'Dach', 'Turm', 'Garage', 'Moschee', 'Hospital', 'Zelt', 'Haus', 'Wand', 'Bank', 'Schutt', 'Hütte']
d["a4a_nature"] = ['Land', 'Klippe', 'Hügel', 'Schlucht', 'Felsen', 'Meer', 'See', 'Küste', 'Land', 'Berg', 'Teich', 'Gipfel', 'Lava', 'Höhle', 'Düne', 'Insel', 'Wald', 'Wüste', 'Eisberg']
d["a4a_jobs"] = ['Clown', 'Ingenieur', 'Priester', 'Veterinär', 'Richter', 'Koch', 'Athlet', 'Bibliothekar', 'juggler', 'Polizei', 'Klempner', 'Dienstmarke', 'Königin', 'Farmer', 'Magier', 'Ritter', 'Arzt', 'Maurer', 'Reiniger', 'Lehrer', 'Jäger', 'Soldat', 'Musiker', 'Anwalt', 'Fischer', 'Prinzessin', 'Feuerwehrmann', 'Nonne', 'Pirat', 'Cowboy', 'Elektriker', 'Krankenschwester', 'König', 'Präsident', 'Sekretär', 'Zimmermann', 'Jockey', 'Arbeiter', 'Mechaniker', 'Pilot', 'Schauspieler', 'Koch', 'Student', 'Schlachter', 'Verkäufer', 'Prinz', 'Papst', 'Matrose', 'Boxer', 'Tänzer', 'Trainer', 'Astronaut', 'Maler', 'Anestesist', 'Wissenschaftler']
d["a4a_fruit_n_veg"] = ['Karotte', 'Brombeeren', 'Sellerie', 'Rübe', 'Kakao', 'Pfirsisch', 'Melone', 'Grapefruit', 'Broccoli', 'Weintrauben', 'Spinat', 'Feige', 'Kern', 'Rettich', 'Tomate', 'Kiwi', 'Spargel', 'Oliven', 'Gurken', 'Bohnen', 'Erdbeere', 'Pfeffer', 'raspberry', 'Aprikose', 'Kartoffel', 'Erbse', 'Kohl', 'Kirsche', 'squash', 'Blaubeeren', 'Birne', 'Orange', 'Kürbis', 'Avocado', 'Knoblauch', 'Zwiebel', 'Apfel', 'Limette', 'Blumenkohl', 'Mango', 'Kopfsalat', 'Zitrone', 'Aubergine', 'Artischocke', 'Pflaumen', 'Lauch', 'Banane', 'Papaya']
d["a4a_transport"] = ['Segel', 'Taxi', 'Auto', 'Rad', 'Floß', 'Pedal', 'Bus', 'Lenker', 'Boot', 'Truck', 'Schlitten', 'Teppich', 'Motorrad', 'Zug', 'Schiff', 'Van', 'Kanu', 'Rakete', 'Mast', 'Schlitten', 'Fahrrad']