# -*- coding: utf-8 -*-

d = dict()
d["a4a_animals"] = ['vaca', 'pavo', 'camarón', 'lobo', 'pantera', 'panda', 'garza', 'almeja', 'poni', 'ratón', 'pug', 'coala', 'rana', 'mariquita', 'gorila', '<llama>', 'buitre', 'hámster', 'pájaro', 'estrella de mar', 'cuervo', 'periquito', 'oruga', 'tigre', 'colibrí', 'piraña', 'cerdo', 'escorpión', 'zorro', 'leopardo', 'iguana', 'delfín', 'murciélago', 'pollito', 'cangrejo', 'gallina', 'avispa', 'camaleón', 'ballena', 'erizo', 'cervatillo', 'alce', 'abeja', 'víbora', '<shrike>', 'burro', '<guinea pig>', 'perezoso', 'caballo', '<penguin>', 'nutria', 'oso', 'cebra', 'avestruz', 'camello', 'antílope', 'lémur', 'paloma', 'lama', 'topo', '<ray>', '<ram>', 'mofeta', 'medusa', 'oveja', 'tiburón', 'gatito', 'ciervo', 'caracol', 'flamenco', 'conejo', 'ostra', 'castor', 'gorrión', 'paloma', 'águila', 'escarabajo', 'hipopótamo', 'búho', 'cobra', 'salamandra', 'oca', 'canguro', 'libélula', 'sapo', 'pelícano', 'calamar', '<lion cub>', 'jaguar', 'pato', 'lagartija', 'rinoceronte', 'hiena', 'buey', 'pavo real', 'loro', 'alce', 'caimán', 'hormiga', 'cabra', '<baby rabbit>', 'león', 'ardilla', 'zarigüeya', 'chimpancé', 'ciervo', '<gopher>', 'elefante', 'jirafa', 'araña', 'cachorro', 'arrendajo', '<seal>', 'gallo', 'tortuga', 'toro', 'gato', 'rata', 'babosa', 'búfalo', 'mirlo', 'cisne', 'langosta', 'perro', 'mosquito', 'serpiente', 'pollo', 'oso hormiguero']
d["a4a_sport"] = ['judo', 'piscina', 'ciclista', 'estirar', 'casco', '<ice skating>', 'caminar', 'correr', 'nadar', 'salto', 'caminata', '<boxing>', 'hockey', 'carrera', 'lanzar', 'patinar', 'ganar', 'agacharse', 'esquiar', 'golf', '<whistle>', 'antorcha', '<sailing>', 'derecho', 'tenis', 'saltar', 'remo', 'footing', 'cuerda']
d["a4a_body"] = ['dentadura', 'mejilla', 'tobillo', 'rodilla', 'dedo del pie', 'músculo', 'boca', '<feet>', 'mano', 'codo', 'cabello', 'pestaña', 'barba', '<belly button>', 'pulgar', 'pecho', 'fosa nasal', 'nariz', 'cadera', 'brazo', 'ceja', 'puño', 'cuello', 'muñeca', 'garganta', '<eye>', 'pierna', 'espina', 'oreja', 'dedo', 'pie', 'trenza', 'cara', 'espalda', 'mentón', 'nalgas', 'muslo', 'vientre']
d["a4a_people"] = ['chica', 'masculino', 'hijo', '<mates>', '<friends>', 'bebé', 'niño', 'papá', 'mama', '<twin boys>', '<brothers>', 'hombre', 'madre', 'abuelo', 'familia', 'femenino', 'esposa', 'marido', 'novia', '<madam>', 'abuela', 'pareja', 'mozo', '<twin girls>', 'tribu', 'niño', '<sisters>', 'mujer', 'dama']
d["a4a_food"] = ['caramelo', 'salchicha', 'hamburguesa', '<steak>', 'dulce de chocolate', 'rosquilla', 'coco', 'arroz', '<ice cream>', 'jalea', '<yoghurt>', 'postre', '<pretzel>', '<peanut>', 'mermelada', 'banquete', 'galleta', '<bacon>', 'especia', 'café', 'pastel', 'limonada', 'chocolate', '<water bottle>', 'almuerzo', 'hielo', 'azúcar', 'salsa', 'sopa', 'zumo', 'patata frita', 'pastel', '<mashed potatoes>', '<tea>', 'brioche', 'queso', '<beef>', 'sándwich', '<slice>', 'chispas', 'pizza', 'harina', 'chicle', 'espagueti', 'asado', 'guiso', 'untar', 'carne', 'leche', 'comida', 'maíz', 'pan', 'nuez', 'huevo', '<hot dog>', 'jamón']
d["a4a_clothes_n_accessories"] = ['<jewellery>', 'calcetín', 'chaqueta', 'talón', 'bata', '<shorts>', 'bolsillo', 'collar', 'sudadera', 'uniforme', 'impermeable', '<trousers>', '<sunglasses>', 'abrigo', 'jersey', 'camisa', 'sandalia', 'arreglada', '<pyjamas>', 'falda', '<zip>', '<shoes>', 'joya', '<tie>', 'zapatilla', '<gloves>', 'sombrero', 'manga', 'gorra', '<swimming suit>', '<trainer>', 'chaleco', 'gafas', 'cordón', 'parche', 'bufanda', 'zapato', 'botón', 'vestir', 'faja', '<shoe sole>', 'manto', 'pantalones', 'quimono', '<overalls>']
d["a4a_actions"] = ['lamer', 'mate', 'pedir', '<fell>', 'arañar', 'tocar', 'olfatear', 'ver', 'escalada', 'cavar', 'aullar', 'dormir', 'explorar', 'dibujar', 'abrazar', 'enseñar', 'siesta', 'arcilla', 'pescar', 'palmear', 'llorar', 'cantar', 'encontrarse', 'vender', 'picotear', 'batir', 'arrodillarse', 'encontrar', 'bailar', 'toser', 'cortar', 'pensar', 'ladrido', 'hablar', 'animar', '<bake>', 'escribir', '<punch>', '<strum>', 'estudiar', 'arar', 'sueño', 'buzón', 'inmersión', 'susurrar', 'sollozar', 'sacudir', 'dar de comer', 'gatear', 'campamento', 'derramar', 'limpiar', 'gritar', 'rasgar', 'flotar', 'estirar', '<ate>', 'beso', 'sentarse', 'escotilla', 'guiño', 'escuchar', 'besar', 'jugar', 'lavar', 'charlar', 'conducir', 'beber', 'volar', '<juggle>', 'poco', '<sweep>', 'mirarse', 'tejer', 'levantar', 'traer', 'leer', 'croar', 'mirar fijamente', 'comer']
d["a4a_construction"] = ['faro', 'puerta', 'circo', 'iglesia', '<kennel>', 'templo', 'humo', 'chimenea', 'ladrillo', 'bien', 'calle', 'castillo', 'almacenar', 'escalera', 'escuela', 'granja', 'puente', 'presa', 'pirámide', 'granero', 'molino', 'ventana', 'cabaña', 'peldaño', 'tienda', 'cobertizo', 'techo', 'campanar', 'garaje', 'mezquita', 'hospital', 'tienda', 'casa', 'pared', 'banco', 'contraventana', 'cabaña']
d["a4a_nature"] = ['terreno', 'acantilado', 'colina', 'cañón', 'roca', 'mar', 'lago', 'costa', 'orilla', 'montaña', 'estanque', 'pico', 'lava', 'cueva', 'duna', 'isla', 'bosque', 'desierto', 'iceberg']
d["a4a_jobs"] = ['payaso', 'ingeniero', 'sacerdote', 'veterinario', 'juez', 'cocinero', 'atleta', 'bibliotecaria', 'malabarista', '<policeman>', 'fontanero', 'insignia', 'reina', 'agricultor', '<magician>', 'caballero', 'médico', 'albañil', '<cleaner>', 'maestro', 'cazador', 'soldado', 'músico', 'abogado', 'pescador', 'princesa', 'bombero', 'monja', 'pirata', 'vaquero', 'electricista', 'enfermera', 'rey', 'presidente', '<office worker>', 'carpintero', 'jockey', 'obrero', 'mecánico', 'piloto', 'actor', 'cocinar', 'estudiante', 'carnicero', 'contable', 'príncipe', 'papa', 'marinero', 'boxeador', '<ballet dancer>', 'entrenador', 'astronauta', '<painter>', '<anaesthesiologist>', '<scientist>']
d["a4a_fruit_n_veg"] = ['zanahoria', '<blackberries>', 'apio', 'nabo', 'cacao', 'melocotón', 'melón', 'pomelo', 'brócoli', '<grapes>', 'espinacas', 'higo', 'núcleo', 'rábano', '<tomato>', 'kiwi', 'espárragos', '<olives>', '<cucumbers>', '<beans>', 'fresa', 'pimiento', 'frambuesa', 'albaricoque', '<potatoes>', '<peas>', 'repollo', '<cherries>', 'calabacín', '<blueberries>', 'pera', 'naranja', 'calabaza', 'aguacate', 'ajo', 'cebolla', 'manzana', 'lima', 'coliflor', 'mango', 'lechuga', 'limón', '<aubergine>', '<artichokes>', '<plums>', 'puerro', '<bananas>', 'papaya']
d["a4a_transport"] = ['navegar', 'taxi', 'coche', 'bicicleta', 'balsa', 'pedal', 'autobús', 'manillar', 'bote', 'camión', 'trineo', 'alfombra', 'motocicleta', 'tren', 'barco', 'furgoneta', 'canoa', 'cohete', 'mástil', '<sledge>', '<bicycle>']