# -*- coding: utf-8 -*-

d = dict()
d["a4a_animals"] = ['vaca', 'pavo', 'camarón', 'lobo', 'pantera', 'panda', 'garza', 'almeja', 'poni', 'ratón', 'pug', 'koala', 'rana', 'mariquita', 'gorila', 'llama', 'buitre', 'hámster', 'pájaro', 'estrella de mar', 'cuervo', 'periquito', 'oruga', 'tigre', 'colibrí', 'piraña', 'cerdo', 'escorpión', 'zorro', 'leopardo', 'iguana', 'delfín', 'murciélago', 'pollito', 'cangrejo', 'gallina', 'avispa', 'camaleón', 'ballena', 'erizo', 'cervatillo', 'alce', 'abeja', 'víbora', 'alcaudón', 'burro', 'conejillo de indias', 'perezoso', 'caballo', 'pingüino', 'nutria', 'oso', 'cebra', 'avestruz', 'camello', 'antílope', 'lémur', 'paloma', 'lama', 'topo', 'mantaraya', 'carnero', 'mofeta', 'medusa', 'oveja', 'tiburón', 'gatito', 'ciervo', 'caracol', 'flamenco', 'conejo', 'ostra', 'castor', 'gorrión', 'paloma', 'águila', 'escarabajo', 'hipopótamo', 'búho', 'cobra', 'salamandra', 'ganso', 'canguro', 'libélula', 'sapo', 'pelícano', 'calamar', 'león bebe', 'jaguar', 'pato', 'lagartija', 'rinoceronte', 'hiena', 'buey', 'pavo real', 'loro', 'alce', 'caimán', 'hormiga', 'cabra', 'conejito', 'león', 'ardilla', 'zarigüeya', 'chimpancé', 'ciervo', 'perrito de la pradera', 'elefante', 'jirafa', 'araña', 'cachorro', 'arrendajo', 'foca', 'gallo', 'tortuga', 'toro', 'gato', 'rata', 'babosa', 'búfalo', 'mirlo', 'cisne', 'langosta', 'perro', 'mosquito', 'serpiente', 'pollo', 'oso hormiguero']
d["a4a_sport"] = ['judo', 'piscina', 'ciclista', 'estirar', 'casco', 'patinaje sobre hielo', 'caminar', 'correr', 'nadar', 'salto', 'caminata', 'boxeo', 'hockey', 'carrera', 'lanzar', 'patinar', 'ganar', 'agacharse', 'esquiar', 'golf', 'silbato', 'antorcha', 'navegar', 'derecho', 'tenis', 'saltar', 'remo', 'footing', 'cuerda']
d["a4a_body"] = ['dentadura', 'mejilla', 'tobillo', 'rodilla', 'dedo del pie', 'músculo', 'boca', 'pies', 'mano', 'codo', 'cabello', 'pestaña', 'barba', 'ombligo', 'pulgar', 'pecho', 'fosa nasal', 'nariz', 'cadera', 'brazo', 'ceja', 'puño', 'cuello', 'muñeca', 'garganta', 'ojo', 'pierna', 'espina', 'oreja', 'dedo', 'pie', 'trenza', 'cara', 'espalda', 'mentón', 'nalgas', 'muslo', 'vientre']
d["a4a_people"] = ['chica', 'masculino', 'hijo', 'amigos', 'amigos', 'bebé', 'niño', 'papá', 'mama', 'mellizos', 'hermanos', 'hombre', 'madre', 'abuelo', 'familia', 'femenino', 'esposa', 'marido', 'novia', 'señora', 'abuela', 'pareja', 'mozo', 'mellizas', 'tribu', 'niño', 'hermanas', 'mujer', 'dama']
d["a4a_food"] = ['caramelo', 'salchicha', 'hamburguesa', 'carne', 'dulce de chocolate', 'rosquilla', 'coco', 'arroz', 'helado', 'jalea', 'yogur', 'postre', 'pretzel', 'maní', 'mermelada', 'banquete', 'galleta', 'tocino', 'especia', 'café', 'pastel', 'limonada', 'chocolate', 'agua embotellada', 'almuerzo', 'hielo', 'azúcar', 'salsa', 'sopa', 'zumo', 'patata frita', 'pastel', 'puré de papa', 'té', 'brioche', 'queso', 'carne de res', 'sándwich', 'rebanada', 'chispas', 'pizza', 'harina', 'chicle', 'espagueti', 'asado', 'guiso', 'untar', 'carne', 'leche', 'comida', 'maíz', 'pan', 'nuez', 'huevo', 'hot dog', 'jamón']
d["a4a_clothes_n_accessories"] = ['joyería', 'calcetín', 'chaqueta', 'talón', 'bata', 'shorts', 'bolsillo', 'collar', 'sudadera', 'uniforme', 'impermeable', 'pantalones', 'gafas de sol', 'abrigo', 'jersey', 'camisa', 'sandalia', 'arreglada', 'pijama', 'falda', 'cierre', 'zapatos', 'joya', 'corbata', 'zapatilla', 'guantes', 'sombrero', 'manga', 'gorra', 'traje de baño', 'ropa deportiva', 'chaleco', 'gafas', 'cordón', 'parche', 'bufanda', 'zapato', 'botón', 'vestir', 'faja', 'suela del zapato', 'manto', 'pantalones', 'quimono', 'overol']
d["a4a_actions"] = ['lamer', 'mate', 'pedir', 'cayó', 'arañar', 'tocar', 'olfatear', 'ver', 'escalada', 'cavar', 'aullar', 'dormir', 'explorar', 'dibujar', 'abrazar', 'enseñar', 'siesta', 'arcilla', 'pescar', 'palmear', 'llorar', 'cantar', 'encontrarse', 'vender', 'picotear', 'batir', 'arrodillarse', 'encontrar', 'bailar', 'toser', 'cortar', 'pensar', 'ladrido', 'hablar', 'animar', 'hornear', 'escribir', 'golpear', 'rasguear', 'estudiar', 'arar', 'sueño', 'buzón', 'inmersión', 'susurrar', 'sollozar', 'sacudir', 'dar de comer', 'gatear', 'campamento', 'derramar', 'limpiar', 'gritar', 'rasgar', 'flotar', 'estirar', 'comió', 'beso', 'sentarse', 'escotilla', 'guiño', 'escuchar', 'besar', 'jugar', 'lavar', 'charlar', 'conducir', 'beber', 'volar', 'malabarismo', 'poco', 'barrer', 'mirarse', 'tejer', 'levantar', 'traer', 'leer', 'croar', 'mirar fijamente', 'comer']
d["a4a_construction"] = ['faro', 'puerta', 'circo', 'iglesia', 'perrera', 'templo', 'humo', 'chimenea', 'ladrillo', 'bien', 'calle', 'castillo', 'almacenar', 'escalera', 'escuela', 'granja', 'puente', 'presa', 'pirámide', 'granero', 'molino', 'ventana', 'cabaña', 'peldaño', 'tienda', 'cobertizo', 'techo', 'campanar', 'garaje', 'mezquita', 'hospital', 'tienda', 'casa', 'pared', 'banco', 'contraventana', 'cabaña']
d["a4a_nature"] = ['terreno', 'acantilado', 'colina', 'cañón', 'roca', 'mar', 'lago', 'costa', 'orilla', 'montaña', 'estanque', 'pico', 'lava', 'cueva', 'duna', 'isla', 'bosque', 'desierto', 'iceberg']
d["a4a_jobs"] = ['payaso', 'ingeniero', 'sacerdote', 'veterinario', 'juez', 'cocinero', 'atleta', 'bibliotecaria', 'malabarista', 'policía', 'fontanero', 'insignia', 'reina', 'agricultor', 'mago', 'caballero', 'médico', 'albañil', 'persona de limpieza', 'maestro', 'cazador', 'soldado', 'músico', 'abogado', 'pescador', 'princesa', 'bombero', 'monja', 'pirata', 'vaquero', 'electricista', 'enfermera', 'rey', 'presidente', 'oficinista', 'carpintero', 'jockey', 'obrero', 'mecánico', 'piloto', 'actor', 'cocinar', 'estudiante', 'carnicero', 'contable', 'príncipe', 'papa', 'marinero', 'boxeador', 'bailarina de ballet', 'entrenador', 'astronauta', 'pintor', 'anestesiólogo', 'científico']
d["a4a_fruit_n_veg"] = ['zanahoria', 'moras', 'apio', 'nabo', 'cacao', 'melocotón', 'melón', 'pomelo', 'brócoli', 'uvas', 'espinacas', 'higo', 'núcleo', 'rábano', 'tomate', 'kiwi', 'espárragos', 'aceituna', 'pepino', 'frijoles', 'fresa', 'pimiento', 'frambuesa', 'albaricoque', 'papas', 'guisantes', 'repollo', 'cerezas', 'calabacín', 'arándano', 'pera', 'naranja', 'calabaza', 'aguacate', 'ajo', 'cebolla', 'manzana', 'lima', 'coliflor', 'mango', 'lechuga', 'limón', 'berenjena', 'alcachofas', 'ciruela', 'puerro', 'plátano', 'papaya']
d["a4a_transport"] = ['navegar', 'taxi', 'coche', 'bicicleta', 'balsa', 'pedal', 'autobús', 'manillar', 'bote', 'camión', 'trineo', 'alfombra', 'motocicleta', 'tren', 'barco', 'furgoneta', 'canoa', 'cohete', 'mástil', 'trineo', 'bicicleta']