# -*- coding: utf-8 -*-

d = dict()
d["a4a_animals"] = ['lehmä', 'kalkkuna', 'katkarapu', 'susi', 'pantteri', 'panda', 'harakka', 'simpukka', 'poni', 'hiiri', 'mopsi', 'koala', 'sammakko', 'leppäkerttu', 'gorilla', '<llama>', 'petolintu', '<hamster>', 'lintu', 'meritähti', 'varis', 'papukaija', 'toukka', 'tiikeri', 'kolibri', 'piraija', 'sika', 'skorpioni', 'kettu', 'leopardi', 'iguaani', 'delfiini', 'lepakko', 'kananpoika', 'rapu', 'kana', 'ampiainen', 'kameleontti', 'valas', 'siili', 'kellanruskea', 'hirvi', 'mehiläinen', 'kyy', '<shrike>', '<donkey>', '<guinea pig>', 'laiskiainen', 'hevonen', '<penguin>', 'saukko', 'karhu', 'seepra', 'strutsi', 'kameli', 'antilooppi', 'maki', 'kyyhkynen', 'laama', 'myyrä', '<ray>', '<ram>', 'haisunäätä', 'meduusa', 'lammas', 'hai', 'kissanpentu', 'kauris', 'etana', 'flamingo', 'kani', 'osteri', 'majava', 'pääskynen', 'kyyhkynen', 'kotka', 'koppakuoriainen', 'virtahepo', 'pöllö', 'kobra', 'salamanteri', 'hanhi', 'kenguru', 'sudenkorento', 'rupikonna', 'pelikaani', 'mustekala', '<lion cub>', 'jaguaari', 'ankka', 'lisko', 'sarvikuono', 'hyeena', 'härkä', 'riikinkukko', 'papukaija', 'hirvi', 'alligaattori', 'muurahainen', 'vuohi', '<baby rabbit>', 'leijona', 'orava', 'opossumi', 'simpanssi', 'naaraspeura', '<gopher>', '<elephant>', 'kirahvi', 'hämähäkki', 'koiranpentu', 'närhi', '<seal>', '<rooster>', 'kilpikonna', 'härkä', 'kissa', 'rotta', 'etana', 'puhveli', 'mustarastas', 'joutsen', 'hummeri', 'koira', 'hyttynen', 'käärme', 'kana', 'muurahaiskarhu']
d["a4a_sport"] = ['judo', 'uima-allas', 'ratsastaa', 'venyttää', 'kypärä', '<ice skating>', 'kävellä', 'juosta', 'uinti', 'hypätä', 'patikkaretki', '<boxing>', 'jääkiekko', 'kisa', 'heitto', 'luistelu', 'voittaa', 'kyykistyä', 'hiihto', 'golf', '<whistle>', 'soihtu', '<sailing>', 'seistä', 'tennis', 'hypätä', 'soutu', 'hölkkä', 'köysi']
d["a4a_body"] = ['hampaat', 'poski', 'nilkka', 'polvi', 'varvas', 'lihas', 'suu', '<feet>', 'käsi', 'kyynärpää', 'tukka', 'silmäripsi', 'parta', '<belly button>', 'peukalo', 'rinta', 'sierain', 'nenä', 'lonkka', 'käsivarsi', '<eyebrow>', 'nyrkki', 'niska', 'ranne', 'kurkku', '<eye>', 'sääri', 'selkäranka', 'korva', 'sormi', 'jalka', 'letti', 'kasvot', 'selkä', 'leuka', 'takamus', 'reisi', 'masu']
d["a4a_people"] = ['tyttö', '<male>', 'poika', '<mates>', '<friends>', '<baby>', 'lapsi', 'isä', 'äiti', '<twin boys>', '<brothers>', 'mies', 'äiti', '<grandfather>', 'perhe', '<female>', 'vaimo', 'aviomies', 'morsian', '<madam>', 'isoäiti', 'pariskunta', 'poika', '<twin girls>', 'heimo', 'poika', '<sisters>', 'nainen', 'rouva']
d["a4a_food"] = ['karkki', 'makkara', 'hampurilainen', '<steak>', 'toffee', 'donitsi', 'kookos', 'riisi', '<ice cream>', 'hyytelö', '<yoghurt>', 'jälkiruoka', '<pretzel>', '<peanut>', 'hillo', 'juhla', 'keksi', '<bacon>', 'mauste', 'kahvi', 'piirakka', 'limonadi', 'suklaa', '<water bottle>', 'lounas', 'jää', 'sokeri', 'kastike', 'keitto', 'mehu', 'ranskalaiset', 'kakku', '<mashed potatoes>', '<tea>', 'pulla', 'juusto', '<beef>', 'voileipä', '<slice>', 'nonparelli', 'pitsa', 'jauhot', 'purukumi', 'spagetti', 'paisti', 'muhennos', 'levittää', 'liha', 'maito', 'ateria', 'maissi', 'leipä', 'saksanpähkinä', 'kananmuna', '<hot dog>', 'kinkku']
d["a4a_clothes_n_accessories"] = ['<jewellery>', 'sukka', 'takki', 'kantapää', 'työtakki', '<shorts>', 'tasku', 'kaulakoru', 'huppari', 'univormu', 'sadetakki', '<trousers>', '<sunglasses>', 'takki', 'villapaita', 'paita', 'sandaalit', 'puku', '<pyjamas>', 'mekko', '<zip>', '<shoes>', 'jalokivi', '<tie>', 'tossut', '<gloves>', 'hattu', 'hiha', 'lakki', '<swimming suit>', '<trainer>', 'liivi', 'silmälasit', 'kengännauha', 'paikka', 'huivi', 'kenkä', 'nappi', 'puku', 'liina', '<shoe sole>', 'kylpytakki', 'housut', 'kimono', '<overalls>']
d["a4a_actions"] = ['nuolla', 'läimäyttää', 'rukoilla', 'kaatua', 'raapia', 'koskea', 'nuuhkaista', 'nähdä', 'nousu', 'kaivaa', 'ulvoa', 'nukkua', 'tutkia', 'piirtää', 'halata', 'opettaa', 'torkkua', 'savi', 'ottaa kiinni', 'taputtaa', 'itkeä', 'laulaa', 'tavata', '<sell>', 'nokkia', 'lyödä', 'polvistua', 'löytää', 'tanssi', 'yskiä', 'leikata', 'ajatella', 'haukkua', 'puhua', 'tervehdys', '<bake>', 'kirjoittaa', '<punch>', '<strum>', 'opiskella', 'kyntää', 'nähdä unta', 'lähettää', 'sukellus', 'kuiskata', 'nyyhkytys', 'ravistaa', 'syöttää', 'ryömiä', 'leiri', 'läikyttää', 'siivota', 'kirkua', 'repiä', 'kellua', 'vetää', '<ate>', 'suudella', 'istua', 'kuoriutua', 'räpäyttää', 'kuulla', 'pussata', 'leikkiä', 'pestä', 'jutella', 'ajaa', 'juoma', 'lentää', '<juggle>', 'bitti', '<sweep>', 'katsoa', 'kutoa', 'hissi', 'noutaa', 'lukea', 'kurnuttaa', 'tuijottaa', 'syödä']
d["a4a_construction"] = ['majakka', 'ovi', 'sirkus', '<church>', '<kennel>', 'temppeli', 'savu', 'savupiippu', 'tiili', '<well>', 'katu', 'linna', 'kauppa', 'portaikko', 'koulu', 'maatila', 'silta', 'pato', 'pyramidi', 'lato', 'mylly', 'ikkuna', 'hytti', 'porras', 'kauppa', 'vaja', 'katto', 'kirkontorni', 'autotalli', 'moskeija', 'sairaala', 'teltta', 'talo', 'seinä', 'rinne', 'ikkunaluukku', 'maja']
d["a4a_nature"] = ['maa', 'kallio', 'mäki', 'kanjoni', 'lohkare', 'meri', 'järvi', 'rannikko', 'ranta', 'vuori', 'lampi', 'huippu', 'laava', 'luola', 'dyyni', 'saari', 'metsä', 'aavikko', 'jäävuori']
d["a4a_jobs"] = ['pelle', 'insinööri', 'pappi', 'eläinlääkäri', 'tuomari', 'kokki', 'yleisurheilija', 'kirjastonhoitaja', 'jonglööri', '<policeman>', 'putkiasentaja', 'virkamerkki', 'kuningatar', 'maanviljelijä', '<magician>', 'ritari', 'lääkäri', 'muurari', '<cleaner>', 'opettaja', 'metsästäjä', 'sotilas', 'muusikko', 'juristi', 'kalastaja', 'prinsessa', 'palomies', 'nunna', 'merirosvo', 'cowboy', 'sähköasentaja', 'sairaanhoitaja', 'kuningas', 'presidentti', '<office worker>', 'puuseppä', 'jockey', 'työntekijä', 'mekaanikko', 'ohjaaja', 'näyttelijä', 'keittää', 'opiskelija', 'lihakauppias', 'kirjanpitäjä', 'prinssi', 'paavi', 'merimies', 'nyrkkeilijä', '<ballet dancer>', 'valmentaja', 'avaruuslentäjä', '<painter>', '<anaesthesiologist>', '<scientist>']
d["a4a_fruit_n_veg"] = ['porkkana', '<blackberries>', 'selleri', 'nauris', 'kaakao', 'persikka', 'meloni', 'ananas', 'parsakaali', '<grapes>', 'pinaatti', 'viikuna', 'ydin', 'retiisi', '<tomato>', 'kiivi', 'parsa', '<olives>', '<cucumbers>', '<beans>', 'mansikka', 'pippuri', 'vadelma', 'aprikoosi', '<potatoes>', '<peas>', 'kaali', '<cherries>', 'kurpitsa', '<blueberries>', 'päärynä', 'appelsiini', 'kurpitsa', 'avokado', 'valkosipuli', 'sipuli', 'omena', 'limetti', 'kukkakaali', 'mango', 'lehtisalaatti', 'sitruuna', '<aubergine>', '<artichokes>', '<plums>', 'purjo', '<bananas>', 'papaija']
d["a4a_transport"] = ['purje', 'taksi', 'auto', 'polkupyörä', 'lautta', 'poljin', 'linja-auto', 'kahva', 'vene', 'kuorma-auto', 'kelkka', 'matto', 'moottoripyörä', 'juna', 'laiva', 'pakettiauto', 'kanootti', 'raketti', 'masto', '<sledge>', '<bicycle>']