# -*- coding: utf-8 -*-

d = dict()


d["a4a_animals"] = ['lehmä', 'kalkkuna', 'katkarapu', 'susi', 'pantteri', 'panda', 'harakka', 'simpukka', 'poni', 'hiiri', 'mopsi', 'koala', 'sammakko', 'leppäkerttu', 'gorilla', 'laama', 'petolintu', 'hamsteri', 'lintu', 'meritähti', 'varis', 'papukaija', 'toukka', 'tiikeri', 'kolibri', 'piraija', 'sika', 'skorpioni', 'kettu', 'leopardi', 'iguaani', 'delfiini', 'lepakko', 'kananpoika', 'rapu', 'kana', 'ampiainen', 'kameleontti', 'valas', 'siili', 'kellanruskea', 'hirvi', 'mehiläinen', 'kyy', 'leppälintu', 'aasi', 'marsu', 'laiskiainen', 'hevonen', 'pingviini', 'saukko', 'karhu', 'seepra', 'strutsi', 'kameli', 'antilooppi', 'maki', 'kyyhkynen', 'laama', 'myyrä', 'rausku', 'pässi', 'haisunäätä', 'meduusa', 'lammas', 'hai', 'kissanpentu', 'kauris', 'etana', 'flamingo', 'kani', 'osteri', 'majava', 'pääskynen', 'kyyhkynen', 'kotka', 'koppakuoriainen', 'virtahepo', 'pöllö', 'kobra', 'salamanteri', 'hanhi', 'kenguru', 'sudenkorento', 'rupikonna', 'pelikaani', 'mustekala', 'leijonanpentu', 'jaguaari', 'ankka', 'lisko', 'sarvikuono', 'hyeena', 'härkä', 'riikinkukko', 'papukaija', 'hirvi', 'alligaattori', 'muurahainen', 'vuohi', 'kaninpoikanen', 'leijona', 'orava', 'opossumi', 'simpanssi', 'naaraspeura', 'taskurotta', 'norsu', 'kirahvi', 'hämähäkki', 'koiranpentu', 'närhi', 'hylje', 'kukko', 'kilpikonna', 'härkä', 'kissa', 'rotta', 'etana', 'puhveli', 'mustarastas', 'joutsen', 'hummeri', 'koira', 'hyttynen', 'käärme', 'kana', 'muurahaiskarhu']
d["a4a_sport"] = ['judo', 'uima-allas', 'ratsastaa', 'venyttää', 'kypärä', 'luistelu', 'kävellä', 'juosta', 'uinti', 'hypätä', 'patikkaretki', 'nyrkkeily', 'jääkiekko', 'kisa', 'heitto', 'luistelu', 'voittaa', 'kyykistyä', 'hiihto', 'golf', 'pilli', 'soihtu', 'purjehdus', 'seistä', 'tennis', 'hypätä', 'soutu', 'hölkkä', 'köysi']
d["a4a_body"] = ['hampaat', 'poski', 'nilkka', 'polvi', 'varvas', 'lihas', 'suu', 'jalat', 'käsi', 'kyynärpää', 'tukka', 'silmäripsi', 'parta', 'napa', 'peukalo', 'rinta', 'sierain', 'nenä', 'lonkka', 'käsivarsi', 'kulmakarva', 'nyrkki', 'niska', 'ranne', 'kurkku', 'silmä', 'sääri', 'selkäranka', 'korva', 'sormi', 'jalka', 'letti', 'kasvot', 'selkä', 'leuka', 'takamus', 'reisi', 'masu']
d["a4a_people"] = ['tyttö', 'mies', 'poika', 'kaverit', 'ystävät', 'vauva', 'lapsi', 'isä', 'äiti', 'kaksoispojat', 'veljet', 'mies', 'äiti', 'isoisä', 'perhe', 'nainen', 'vaimo', 'aviomies', 'morsian', 'rouva', 'isoäiti', 'pariskunta', 'poika', 'kaksoistytöt', 'heimo', 'poika', 'siskot', 'nainen', 'rouva']
d["a4a_food"] = ['karkki', 'makkara', 'hampurilainen', 'pihvi', 'toffee', 'donitsi', 'kookos', 'riisi', 'jäätelö', 'hyytelö', 'jogurtti', 'jälkiruoka', 'suolarinkeli', 'maapähkinä', 'hillo', 'juhla', 'keksi', 'pekoni', 'mauste', 'kahvi', 'piirakka', 'limonadi', 'suklaa', 'vesipullo', 'lounas', 'jää', 'sokeri', 'kastike', 'keitto', 'mehu', 'ranskalaiset', 'kakku', 'perunamuusi', 'tee', 'pulla', 'juusto', 'naudanliha', 'voileipä', 'viipale', 'nonparelli', 'pitsa', 'jauhot', 'purukumi', 'spagetti', 'paisti', 'muhennos', 'levittää', 'liha', 'maito', 'ateria', 'maissi', 'leipä', 'saksanpähkinä', 'kananmuna', 'hodari', 'kinkku']
d["a4a_clothes_n_accessories"] = ['korut', 'sukka', 'takki', 'kantapää', 'työtakki', 'shortsit', 'tasku', 'kaulakoru', 'huppari', 'univormu', 'sadetakki', 'housut', 'aurinkolasit', 'takki', 'villapaita', 'paita', 'sandaalit', 'puku', 'yöpuku', 'mekko', 'vetoketju', 'kengät', 'jalokivi', 'solmio', 'tossut', 'hanskat', 'hattu', 'hiha', 'lakki', 'uimapuku', 'lenkkari', 'liivi', 'silmälasit', 'kengännauha', 'paikka', 'huivi', 'kenkä', 'nappi', 'puku', 'liina', 'kengänpohja', 'kylpytakki', 'housut', 'kimono', 'haalarit']
d["a4a_actions"] = ['nuolla', 'läimäyttää', 'rukoilla', 'kaatua', 'raapia', 'koskea', 'nuuhkaista', 'nähdä', 'nousu', 'kaivaa', 'ulvoa', 'nukkua', 'tutkia', 'piirtää', 'halata', 'opettaa', 'torkkua', 'savi', 'ottaa kiinni', 'taputtaa', 'itkeä', 'laulaa', 'tavata', 'myydä', 'nokkia', 'lyödä', 'polvistua', 'löytää', 'tanssi', 'yskiä', 'leikata', 'ajatella', 'haukkua', 'puhua', 'tervehdys', 'leipoa', 'kirjoittaa', 'lyödä', 'rämpyttää', 'opiskella', 'kyntää', 'nähdä unta', 'lähettää', 'sukellus', 'kuiskata', 'nyyhkytys', 'ravistaa', 'syöttää', 'ryömiä', 'leiri', 'läikyttää', 'siivota', 'kirkua', 'repiä', 'kellua', 'vetää', 'söi', 'suudella', 'istua', 'kuoriutua', 'räpäyttää', 'kuulla', 'pussata', 'leikkiä', 'pestä', 'jutella', 'ajaa', 'juoma', 'lentää', 'jongleerata', 'bitti', 'lakaisi', 'katsoa', 'kutoa', 'hissi', 'noutaa', 'lukea', 'kurnuttaa', 'tuijottaa', 'syödä']
d["a4a_construction"] = ['majakka', 'ovi', 'sirkus', 'kirkko', 'koiratarha', 'temppeli', 'savu', 'savupiippu', 'tiili', 'kaivo', 'katu', 'linna', 'kauppa', 'portaikko', 'koulu', 'maatila', 'silta', 'pato', 'pyramidi', 'lato', 'mylly', 'ikkuna', 'hytti', 'porras', 'kauppa', 'vaja', 'katto', 'kirkontorni', 'autotalli', 'moskeija', 'sairaala', 'teltta', 'talo', 'seinä', 'rinne', 'ikkunaluukku', 'maja']
d["a4a_nature"] = ['maa', 'kallio', 'mäki', 'kanjoni', 'lohkare', 'meri', 'järvi', 'rannikko', 'ranta', 'vuori', 'lampi', 'huippu', 'laava', 'luola', 'dyyni', 'saari', 'metsä', 'aavikko', 'jäävuori']
d["a4a_jobs"] = ['pelle', 'insinööri', 'pappi', 'eläinlääkäri', 'tuomari', 'kokki', 'yleisurheilija', 'kirjastonhoitaja', 'jonglööri', 'poliisi', 'putkiasentaja', 'virkamerkki', 'kuningatar', 'maanviljelijä', 'taikuri', 'ritari', 'lääkäri', 'muurari', 'siivooja', 'opettaja', 'metsästäjä', 'sotilas', 'muusikko', 'juristi', 'kalastaja', 'prinsessa', 'palomies', 'nunna', 'merirosvo', 'cowboy', 'sähköasentaja', 'sairaanhoitaja', 'kuningas', 'presidentti', 'toimistotyöntekijä', 'puuseppä', 'jockey', 'työntekijä', 'mekaanikko', 'ohjaaja', 'näyttelijä', 'keittää', 'opiskelija', 'lihakauppias', 'kirjanpitäjä', 'prinssi', 'paavi', 'merimies', 'nyrkkeilijä', 'balettitanssija', 'valmentaja', 'avaruuslentäjä', 'maalari', 'anestesiologi', 'tutkija']
d["a4a_fruit_n_veg"] = ['porkkana', 'karhunvatukat', 'selleri', 'nauris', 'kaakao', 'persikka', 'meloni', 'ananas', 'parsakaali', 'viinirypäleet', 'pinaatti', 'viikuna', 'ydin', 'retiisi', 'tomaatti', 'kiivi', 'parsa', 'oliivit', 'kurkut', 'pavut', 'mansikka', 'pippuri', 'vadelma', 'aprikoosi', 'perunat', 'herneet', 'kaali', 'kirsikat', 'kurpitsa', 'mustikat', 'päärynä', 'appelsiini', 'kurpitsa', 'avokado', 'valkosipuli', 'sipuli', 'omena', 'limetti', 'kukkakaali', 'mango', 'lehtisalaatti', 'sitruuna', 'munakoiso', 'artisokat', 'luumut', 'purjo', 'banaanit', 'papaija']
d["a4a_transport"] = ['purje', 'taksi', 'auto', 'polkupyörä', 'lautta', 'poljin', 'linja-auto', 'kahva', 'vene', 'kuorma-auto', 'kelkka', 'matto', 'moottoripyörä', 'juna', 'laiva', 'pakettiauto', 'kanootti', 'raketti', 'masto', 'reki', 'polkupyörä']