# -*- coding: utf-8 -*-

d = dict()
d["a4a_animals"] = ['vache', 'dinde', 'crevettes', 'loup', 'panthère', 'panda', 'pie', 'palourde', 'poney', 'souris', 'carlin', 'koala', 'grenouille', 'coccinelle', 'gorille', 'lama', 'vautour', 'hamster', 'oiseau', 'étoile de mer', 'corbeau', 'perruche', 'chenille', 'tigre', 'colibri', 'piranha', 'cochon', 'scorpion', 'renard', 'léopard', 'iguane', 'dauphin', 'chauve-souris', 'poussin', 'crabe', 'poule', 'guêpe', 'caméléon', 'baleine', 'hérisson', 'fauve', 'élan', 'abeille', 'vipère', 'passereaux', 'âne', "cochon d'inde", 'paresseux', 'cheval', 'pingouin', 'loutre', 'ours', 'zèbre', 'autruche', 'chameau', 'antilope', 'lémurien', 'pigeon', 'lama', 'taupe', 'raie', 'bélier', 'putois', 'méduse', 'mouton', 'requin', 'chaton', 'cerf', 'escargot', 'flamant rose', 'lapin', 'huître', 'castor', 'moineau', 'colombe', 'aigle', 'coléoptère', 'hippopotame', 'hibou', 'cobra', 'salamandre', 'oie', 'kangourou', 'libellule', 'crapaud', 'pélican', 'calamar', 'lionceau', 'jaguar', 'canard', 'lézard', 'rhinocéros', 'hyène', 'boeuf', 'paon', 'perroquet', 'wapiti', 'alligator', 'fourmi', 'chèvre', 'petit lapin', 'lion', 'écureuil', 'marsupial', 'chimpanzé', 'daim', 'gaufre', 'éléphant', 'girafe', 'araignée', 'chiot', 'geai', 'phoque', 'coq', 'tortue', 'taureau', 'chat', 'rat', 'limace', 'buffle', 'merle', 'cygne', 'homard', 'chien', 'moustique', 'serpent', 'poulet', 'tamanoir']
d["a4a_sport"] = ['judo', 'piscine', 'vélo', 'étirements', 'casque', 'patinage', 'marche', 'courrir', 'nager', 'sauter', 'randonnée', 'boxe', 'hockey', 'course', 'javelot', 'skate', 'gagner', 'squat', 'ski', 'golf', 'sifflet', 'torche', 'voile', 'stand', 'tennis', 'saut', 'aviron', 'jogging', 'corde']
d["a4a_body"] = ['dents', 'joues', 'cheville', 'genou', 'orteil', 'muscle', 'bouche', 'pieds', 'main', 'coude', 'cheveux', 'cils', 'barbe', 'nombril', 'pouce', 'poitrine', 'narine', 'nez', 'hanche', 'bras', 'sourcils', 'poing', 'cou', 'poignet', 'gorge', 'oeil', 'jambe', 'colonne vertébrale', 'oreille', 'doigt', 'pied', 'tresse', 'visage', 'dos', 'menton', 'bas', 'cuisse', 'ventre']
d["a4a_people"] = ['fille', 'male', 'fils', 'écoliers', 'amis', 'bébé', 'enfant', 'papa', 'maman', 'jumeaux', 'frères', 'homme', 'mère', 'grand-père', 'famille', 'femelle', 'femme', 'mari', 'mariée', 'madame', 'grand-mère', 'couple', 'garçon', 'jumelles', 'tribu', 'garçon', 'soeurs', 'femme', 'dame']
d["a4a_food"] = ['bonbons', 'saucisse', 'hamburger', 'steak', 'fondant', 'beignet', 'noix de coco', 'riz', 'crème glacée', 'gelée', 'yaourt', 'dessert', 'bretzel', 'cacahuète', 'confiture', 'fête', 'cookie', 'bacon', 'épice', 'café', 'tarte', 'limonade', 'chocolat', "bouteille d'eau", 'déjeuner', 'glace', 'sucre', 'sauce', 'soupe', 'jus', 'frites', 'gâteau', 'purée de pomme de terre', 'thé', 'bon', 'fromage', 'boeuf', 'sandwich', 'tranche', 'saupoudrer', 'pizza', 'farine', 'gomme', 'spaghetti', 'rôti', 'ragoût', 'tartiner', 'viande', 'lait', 'repas', 'maïs', 'pain', 'noix', 'oeuf', 'hot dog', 'jambon']
d["a4a_clothes_n_accessories"] = ['bijoux', 'chaussette', 'veste', 'talon', 'blouse', 'short', 'poche', 'collier', 'sweat', 'uniforme', 'imperméable', 'pantalon', 'lunettes de soleil', 'manteau', 'pull', 'chemise', 'sandales', 'costume', 'pyjama', 'jupe', 'braguette', 'chaussures', 'bijou', 'cravate', 'chaussons', 'gants', 'chapeau', 'manche', 'cap', 'maillot de bain', 'survêtement', 'gilet', 'lunettes', 'lacet', 'retouche', 'foulard', 'chaussure', 'bouton', ' robe', 'ceinture', 'chaussure a semelle', 'robe', 'pantalon', 'kimono', 'salopette']
d["a4a_actions"] = ['lécher', 'viser', 'mendier', 'tomber', 'griffer', 'toucher', 'sentir', 'voir', 'grimper', 'creuser', 'hurler', 'dormir', 'explorer', 'dessiner', 'serrer', 'enseigner', 'dormir', 'façonner', 'capturer', 'taper', 'pleurer', 'chanter', 'rencontrer', 'vendre', 'picorer', 'heurter', "s'agenouiller", 'trouver', 'danser', 'tousser', 'couper', 'penser', 'aboyer', 'parler', 'encourager', 'cuisiner', 'écrire', 'frapper', 'jouer', 'étudier', 'labourer', 'rêver', 'poster', 'plonger', 'chuchoter', 'souffrir', 'secouer', 'nourrir', 'ramper', 'camper', 'renverser', 'nettoyer', 'crier', 'déchirer', 'flotter', 'tirer', 'manger', 'embrasser', "s'asseoir", 'éclore', ' clignoter', 'entendre', 'embrasser', 'jouer', 'laver', 'discuter', 'conduire', 'boire', 'voler', 'jongler', 'ronger', 'balayer', 'regarder', 'tricoter', 'soulever', 'rapporter', 'lire', 'croasser', 'impressioner', 'manger']
d["a4a_construction"] = ['phare', 'porte', 'cirque', 'église', 'chenil', 'temple', 'fumée', 'cheminée', 'brique', 'puits', 'rue', 'château', 'magasin', 'escalier', 'école', 'ferme', 'pont', 'barrage', 'pyramide', 'grange', 'moulin', 'fenêtre', 'cabine', 'étape', 'boutique', 'hangar', 'toit', 'clocher', 'garage', 'mosquée', 'hôpital', 'tente', 'maison', 'mur', 'banque', 'volet', 'cabane']
d["a4a_nature"] = ['terre', 'falaise', 'colline', 'canyon', 'rocher', 'mer', 'lac', 'côte', 'rivage', 'montagne', 'étang', 'pic', 'lave', 'grotte', 'dune', 'île', 'forêt', 'désert', 'iceberg']
d["a4a_jobs"] = ['clown', 'ingénieur', 'prêtre', 'vétérinaire', 'juge', 'chef', 'athlète', 'libraire', 'jongleur', 'police', 'plombier', 'insigne', 'reine', 'agriculteur', 'magicien', 'chevalier', 'docteur', 'maçon', 'nettoyeur', 'enseignant', 'chasseur', 'soldat', 'musicien', 'avocat', 'pêcheur', 'princesse', 'pompier', 'nounou', 'pirate', 'cowboy', 'électricien', 'infirmière', 'roi', 'président', 'bureau', 'charpentier', 'jockey', 'travailleur', 'mécanicien', 'pilote', 'acteur', 'cuisinier', 'étudiant', 'boucher', 'comptable', 'prince', 'pape', 'marin', 'boxeur', 'ballet', 'coach', 'astronaute', 'peintre', 'anesthésiste', 'scientifique']
d["a4a_fruit_n_veg"] = ['carotte', 'mûres', 'céleri', 'navet', 'cacao', 'pêche', 'melon', 'pamplemousse', 'brocoli', 'raisin', 'épinards', 'figue', 'noyau', 'radis', 'tomate', 'kiwi', 'asperges', 'olives', 'concombres', 'haricots', 'fraise', 'poivrons', 'framboise', 'abricot', 'pommes de terre', 'pois', 'chou', 'cerises', 'courge', 'myrtille', 'poire', 'orange', 'citrouille', 'avocat', 'ail', 'oignon', 'pomme', 'citon vert', 'chou-fleur', 'mangue', 'laitue', 'citron', 'aubergine', 'artichauts', 'prunes', 'poireau', 'bananes', 'papaye']
d["a4a_transport"] = ['voile', 'taxi', 'voiture', 'vélo', 'radeau', 'pédale', 'bus', 'guidon', 'bateau', 'camion', 'traîneau', 'tapis', 'moto', 'train', 'navire', 'fourgonette', 'canot', 'fusée', 'mât', 'luge', 'bicyclette']