# -*- coding: utf-8 -*-

d = dict()
d["a4a_animals"] = ['mucca', 'tacchino', 'gambero', 'lupo', 'pantera', 'panda', 'gazza', 'conchiglia', 'pony', 'topo', 'carlino', 'koala', 'rana', 'coccinella', 'gorilla', 'lama', 'avvoltoio', 'criceto', 'uccello', 'stella di mare', 'corvo', 'parrocchetto', 'caterpillar', 'tigre', 'colibrì', 'piranha', 'maiale', 'lo scoprione', 'volpe', 'leopardo', 'iguana', 'delfino', 'pipistrello', 'pulcino', 'granchio', 'gallina', 'vespa', 'camaleonte', 'balena', 'riccio', 'cerbiatto', 'alce', 'ape', 'vipera', 'averla', 'asino', "porcellino d'india", 'bradipo', 'cavallo', 'pinguino', 'lontra', 'orso', 'zebra', 'ostrica', 'cammello', 'antilope', 'lemure', 'piccione', 'lama', 'talpa', 'razza', 'muflone', 'puzzola', 'medusa', 'pecora', 'pescecane', 'gattino', 'cervo', 'lumaca', 'fenicottero', 'coniglio', 'ostrica', 'castoro', 'passero', 'colombo', 'aquila', 'lo scarabeo', 'ippopotamo', 'gufo', 'cobra', 'salamandra', 'oca', 'canguro', 'libellula', 'rospo', 'pellicano', 'calamaro', 'leoncino', 'giaguaro', 'anatra', 'iguana', 'rinoceronte', 'iena', 'bue', 'pavone', 'pappagallo', 'alce', 'alligatore', 'formica', 'capra', 'coniglietto', 'leone', 'lo scoiattolo', 'opossum', 'scimmia', 'cerbiatta', 'marmotta', 'elefante', 'giraffa', 'ragno', 'cucciolo', 'ghiandaia', 'foca', 'gallo', 'tartaruga', 'toro', 'gatto', 'ratto', 'lumaca', 'bufalo', 'merlo', 'cigno', 'aragosta', 'cane', 'zanzara', 'serpente', 'gallina', 'formichiere']
d["a4a_sport"] = ['judo', 'piscina', 'andare in bicicletta', 'lo stiramento', 'casco', 'pattinaggio su ghiaccio', 'camminare', 'correre', 'nuotare', 'saltare', 'camminare', 'boxare', 'hockey', 'corsa', 'lanciare', 'pattinare', 'vincere', 'squat', 'sciare', 'golf', 'fischiare', 'torcia', 'navigare', 'sostare', 'tennis', 'saltare', 'remare', 'correre', 'corda']
d["a4a_body"] = ['i denti', 'guancia', 'caviglia', 'ginocchio', 'dito', 'muscolo', 'bocca', 'piede', 'mano', 'gomito', 'i capelli', 'ciglio', 'barba', 'ombelico', 'pollice', 'petto', 'narice', 'naso', 'i fianchi', 'braccio', 'sopracciglio', 'pugno', 'collo', 'polso', 'gola', 'occhio', 'gamba', 'spina dorsale', 'orecchio', 'dito', 'piede', 'treccia', 'faccia', 'schiena', 'mento', 'fondo', 'coscia', 'pancia']
d["a4a_people"] = ['ragazza', 'maschio', 'figlio', 'compagni', 'amici', 'bimbo', 'figlio', 'papà', 'mamma', 'gemelli', 'fratelli', 'uomo', 'madre', 'nonno', 'famiglia', 'femmina', 'moglie', 'marito', 'sposa', 'signora', 'nonna', 'coppia', 'ragazzo', 'gemelle', 'tribù', 'ragazzo', 'sorelle', 'donna', 'signora']
d["a4a_food"] = ['caramella', 'salsiccia', 'hamburger', 'bistecca', 'dolce', 'ciambella', 'noce di cocco', 'riso', 'gelato', 'gelatina', 'yogurt', 'dolce', 'pretzel', 'nocciolina', 'prosciutto', 'festa', 'biscotto', 'bacon', 'spezia', 'caffè', 'torta', 'limonata', 'cioccolato', "bottiglia d'acqua", 'merenda', 'ghiaccio', 'zucchero', 'salsa', 'zuppa', 'succo', 'patatine fritte', 'dolce', 'patate schiacciate', 'te', 'panino', 'formaggio', 'manzo', 'panino', 'fetta', 'spruzzo', 'pizza', 'farina', 'gomma da masticare', 'gli spaghetti', 'arrosto', 'stufato', 'spalmare', 'carne', 'latte', 'pasto', 'pannocchia', 'pane', 'noce', 'uovo', 'hot dog', 'prosciutto']
d["a4a_clothes_n_accessories"] = ['gioielleria', 'calzino', 'giubbotto', 'tallone', 'grembiule', 'pantaloncini', 'tasca', 'collana', 'felpa', 'uniforme', 'impemeabile', 'pantaloni', 'occhiali da sole', 'cappotto', 'pullover', 'camicia', 'sandali', 'abito', 'pigiami', 'gonna', 'cerniera', 'scarpe', 'gioiello', 'legare', 'pantofole', 'guanti', 'cappello', 'manica', 'cappellino', 'costume da bagno', 'allenatore', 'canottiera', 'occhiali', 'laccio da scarpe', 'toppa', 'sciarpa', 'scarpa', 'bottone', 'vestito', 'fascia', 'suola', 'vestaglia', 'pantaloni', 'kimono', 'tuta']
d["a4a_actions"] = ['leccare', 'sbattere', 'pregare', 'cadere', 'graffio', 'toccare', 'annusare', 'vedere', 'salire', 'scavare', 'ululare', 'dormire', 'esplorare', 'disegnare', 'abbracciare', 'insegnare', 'pisolare', 'argilla', 'pescare', 'applaudire', 'piangere', 'cantare', 'incontrare', 'vendere', 'beccare', 'battere', 'inginocchiarsi', 'trovare', 'danzare', 'tossire', 'tagliare', 'pensare', 'abbaiare', 'parlare', 'tifare', 'cuocere', 'scrivere', 'pugno', 'strimpellare', 'studiare', 'dissodare', 'sognare', 'posta', 'nuotare', 'sussurrare', 'singhiozzare', 'scuotere', 'alimentare', 'gattonare', 'accampamento', 'rovesciare', 'pulire', 'urlare', 'strappare', 'galleggiare', 'spingere', 'mangiato', 'baciare', 'sedere', 'schiudere', 'lampeggiare', 'ascoltare', 'sbaciucchiarsi', 'giocare', 'lavare', 'bisbigliare', 'guida', 'caffè', 'volare', 'giocolare', 'bocconcino', 'spazzare', 'guardare', 'lavorare ai ferri', 'sollevare i pesi', 'riportare', 'leggere', 'gracidare', 'lo sguardo', 'mangiare']
d["a4a_construction"] = ['faro', 'porta', 'circo', 'chiesa', 'cuccia', 'tempio', 'fumo', 'camino', 'i mattoni', 'bene', 'via', 'castello', 'negozio', 'scala', 'scuola', 'fattoria', 'ponte', 'diga', 'piramide', 'fienile', 'mulino', 'finestra', 'abitacolo', 'passo', 'negozio', 'capanno', 'tetto', 'campanile', 'garage', 'moschea', 'ospedale', 'tenda', 'casa', 'muro', 'banca', 'otturatore della finestra', 'capanna']
d["a4a_nature"] = ['terra', 'burrone', 'collina', 'canyon', 'roccia', 'mare', 'lago', 'costa', 'bagnasciuga', 'montagna', 'stagno', 'picco', 'lava', 'grotta', 'duna', 'isola', 'foresta', 'deserto', 'iceberg']
d["a4a_jobs"] = ['pagliaccio', 'ingegnere', 'prete', 'veterinario', 'giudice', 'chef', 'atleta', 'bibliotecario', 'giocoliere', 'poliziotto', 'idraulico', 'medaglia', 'regina', 'agricoltore', 'mago', 'cavaliere', 'dottore', 'muratore', 'addetto alle pulizie', 'maestro', 'cacciatore', 'soldato', 'musicista', 'avvocato', 'pescatore', 'principessa', 'pompiere', 'suora', 'pirata', 'cowboy', 'elettricista', 'bambinaia', 're', 'presidente', 'impiegato', 'carpentiere', 'spiritoso', 'lavoratore', 'meccanico', 'pilota', 'attore', 'cuoco', 'studente', 'macellaio', 'contabile', 'principe', 'papa', 'marinaio', 'pugile', 'ballerino di danza classica', 'allenatore', 'astronauta', 'pittore', 'anestesiologo', 'scienziato']
d["a4a_fruit_n_veg"] = ['carota', 'more', 'sedano', 'rapa', 'cacao', 'pesca', 'melone', 'pompelmo', 'broccoli', 'acini', 'spinacio', 'fico', 'nocciolo', 'ravanello', 'pomodoro', 'kiwi', 'asparago', 'oliva', 'cocomero', 'fagioli', 'fragola', 'pepe', 'lampone', 'albicocca', 'patate', 'piselli', 'cavolo', 'ciliege', 'zucca', 'mirtillo', 'pera', 'arancio', 'zucca', 'avocado', 'aglio', 'cipolla', 'mela', 'lime', 'cavolfiore', 'mango', 'lattuga', 'limone', 'melanzana', 'carciofi', 'susine', 'porro', 'banane', 'papaya']
d["a4a_transport"] = ['vela', 'taxi', 'automobile', 'bicicletta', 'zattera', 'pedale', 'bus', 'manubrio', 'barca', 'camion', 'slitta', 'tappeto', 'motociclo', 'treno', 'nave', 'furgone', 'canoa', 'razzo', 'palo', 'slitta', 'bicicletta']