# -*- coding: utf-8 -*-

d = dict()
d["a4a_animals"] = ['koe', 'kalkoen', 'garnaal', 'wolf', 'panter', 'panda', 'ekster', 'mossel', 'pony', 'muis', 'mopshond', 'koala', 'kikker', 'lieveheersbeestje', 'gorilla', 'lama', 'gier', 'hamster', 'vogel', 'zeesterren', 'kraai', 'parkiet', 'rups', 'tijger', 'kolibrie', 'piranha', 'varken', 'schorpioen', 'vos', 'luipaard', 'leguaan', 'dolfijn', 'knuppel', 'kuiken', 'krab', 'kip', 'wesp', 'kameleon', 'walvis', 'egel', 'hertenkalf', 'eland', 'bij', 'adder', 'vogeltje', 'ezel', 'proefkonijn', 'luiaard', 'paard', 'pinguïn', 'otter', 'beer', 'zebra', 'struisvogel', 'kameel', 'antilope', 'maki', 'duif', 'lama', 'mol', 'rog', 'ram', 'stinkdier', 'kwal', 'schaap', 'haai', 'baby katje', 'hert', 'slak', 'flamingo', 'konijn', 'oester', 'bever', 'mus', 'duif', 'adelaar', 'kever', 'nijlpaard', 'uil', 'cobra', 'salamander', 'gans', 'kangoeroe', 'libel', 'pad', 'pelikaan', 'inktvis', 'leeuwenwelp', 'jaguar', 'eend', 'hagedis', 'neushoorn', 'hyena', 'os', 'pauw', 'papegaai', 'eland', 'alligator', 'mier', 'geit', 'babykonijn', 'leeuw', 'eekhoorn', 'opossum', 'chimpansee', 'hinde', 'marmot', 'olifant', 'giraffe', 'spin', 'puppy', 'gaai', 'zegel', 'haan', 'schildpad', 'stier', 'kat', 'ratten', 'naaktslak', 'buffel', 'merel', 'zwaan', 'kreeft', 'hond', 'mug', 'slang', 'kip', 'miereneter']
d["a4a_sport"] = ['judo', 'zwembad', 'ritje', 'rekken', 'helm', 'schaatsen', 'wandel', 'ren', 'zwem', 'huppel', 'wandeltocht', 'boksen', 'hockey', 'race', 'gooi', 'schaats', 'winnen', 'hurkzit', 'ski', 'golf', 'fluiten', 'fakkel', 'zeilen', 'staan', 'tennis', 'spring', 'roeien', 'joggen', 'touw']
d["a4a_body"] = ['tanden', 'wang', 'enkel', 'knie', 'teen', 'spier', 'monding', 'voeten', 'hand', 'elleboog', 'haar', 'wimper', 'baard', 'navel', 'duim', 'borstkas', 'neusgat', 'neus', 'heup', 'arm', 'wenkbrauw', 'vuist', 'nek', 'pols', 'keel', 'oog', 'been', 'ruggengraat', 'oor', 'vinger', 'voet', 'vlecht', 'gezicht', 'rug', 'kin', 'achterste', 'dij', 'buik']
d["a4a_people"] = ['meisje', 'mannetje', 'zoon', 'vrienden', 'vrienden', 'baby', 'kind', 'papa', 'mama', 'tweelingjongens', 'broers', 'man', 'moeder', 'grootvader', 'familie', 'vrouwelijk', 'vrouw', 'echtgenoot', 'bruid', 'mevrouw', 'grootmoeder', 'koppel', 'knaap', 'tweelingmeisjes', 'stam', 'jongen', 'zusters', 'vrouw', 'dame']
d["a4a_food"] = ['snoep', 'worst', 'hamburger', 'biefstuk', 'fudge', 'donut', 'kokosnoot', 'rijst', 'ijs', 'gelei', 'yoghurt', 'dessert', 'pretzel', 'pinda', 'konfituur', 'feestmaal', 'koekje', 'spek', 'kruiden', 'koffie', 'taart', 'limonade', 'chocolade', 'waterfles', 'lunch', 'ijs', 'suiker', 'saus', 'soep', 'sap', 'frieten', 'taart', 'aardappel puree', 'thee', 'broodje', 'kaas', 'rundvlees', 'sandwich', 'plak', 'bestrooi', 'pizza', 'meel', 'kauwgom', 'spaghetti', 'geroosterd', 'stoofpot', 'verspreiden', 'vlees', 'melk', 'maaltijd', 'maïs', 'brood', 'walnoot', 'ei', 'hotdog', 'ham']
d["a4a_clothes_n_accessories"] = ['juwelen', 'sok', 'jas', 'hiel', 'kiel', 'short', 'zak', 'halsketting', 'sweatshirt', 'uniform', 'regenjas', 'broek', 'zonnebril', 'jas', 'trui', 'shirt', 'sandalen', 'pak', "pyjama's", 'rok', 'rits', 'schoenen', 'juweel', 'das', 'pantoffels', 'handschoenen', 'hoed', 'mouw', 'kap', 'badpak', 'trainer', "vesta's", 'glazen', 'schoenveter', 'pleister', 'sjaal', 'schoen', 'knop', 'kleedje', 'sjerp', 'schoenzool', 'badjas', 'broek', 'kimono', 'bovenkleding']
d["a4a_actions"] = ['likken', 'dichtslaan', 'bedelen', 'viel', 'kras', 'aanraken', 'snuffelen', 'zie', 'klimmen', 'graven', 'jammeren', 'slapen', 'verkennen', 'tekenen', 'knuffel', 'lesgeven', 'tukje', 'klei', 'vangen', 'klap', 'huilen', 'zing', 'kennismaken', 'verkopen', 'pikken', 'slaan', 'kniel', 'vinden', 'dans', 'hoesten', 'geknipt', 'denk', 'schors', 'spreken', 'juichen', 'bakken', 'schrijf', 'slaan', 'tokkelen', 'studeren', 'ploeteren', 'droom', 'post', 'duik', 'fluister', 'snikken', 'schudden', 'voederen', 'kruipen', 'kamperen', 'morsen', 'schoonmaken', 'schreeuwen', 'scheur', 'drijven', 'trek', 'heeft  gegeten', 'kus', 'zitten', 'luik', 'knipperen', 'hoor', 'kus', 'spelen', 'was', 'chat', 'rijden', 'om te drinken', 'vlieg', 'goochelen op', 'bit', 'sweep', 'kijk op', 'brei', 'lift', 'haal', 'lees', 'kwaken', 'staren', 'eten']
d["a4a_construction"] = ['vuurtoren', 'deur', 'circus', 'kerk', 'kennel', 'tempel', 'rook', 'schoorsteen', 'baksteen', 'bron', 'straat', 'kasteel', 'winkel', 'trappenhuis', 'school', 'boerderij', 'brug', 'dam', 'piramide', 'schuur', 'molen', 'venster', 'cabine', 'stap', 'winkel', 'loods', 'dak', 'kerktoren', 'garage', 'moskee', 'ziekenhuis', 'tent', 'huis', 'muur', 'bank', 'sluiter', 'hut']
d["a4a_nature"] = ['land', 'rotswand', 'heuvel', 'canyon', 'rots', 'zee', 'het meer', 'kust', 'wal', 'berg', 'vijver', 'topje', 'lava', 'grot', 'duin', 'eiland', 'bos', 'woestijn', 'ijsberg']
d["a4a_jobs"] = ['clown', 'ingenieur', 'priester', 'dierenarts', 'rechter', 'chef-kok', 'atleet', 'bibliothecaris', 'jongleur', 'politieagent', 'loodgieter', 'badge', 'koningin', 'boer', 'goochelaar', 'ridder', 'arts', 'metselaar', 'reiniger', 'leraar', 'jager', 'soldaat', 'muzikant', 'advocaat', 'visser', 'prinses', 'brandweerman', 'zuster', 'piraat', 'cowboy', 'elektricien', 'verpleger', 'koning', 'president', 'kantoormedewerker', 'timmerman', 'jockey', 'werknemer', 'monteur', 'piloot', 'acteur', 'kok', 'student', 'slager', 'boekhouder', 'prins', 'paus', 'matroos', 'bokser', 'balletdanser', 'coach', 'astronaut', 'schilder', 'anesthesist', 'wetenschapper']
d["a4a_fruit_n_veg"] = ['wortel', 'braambessen', 'selderij', 'raap', 'cacao', 'perzik', 'meloen', 'grapefruit', 'broccoli', 'druiven', 'spinazie', 'vijg', 'binnenste', 'radijs', 'tomaat', 'kiwi', 'asperges', 'olijven', 'komkommers', 'bonen', 'aardbei', "paprika's", 'framboos', 'abrikoos', 'aardappelen', 'erwten', 'kool', 'kersen', 'squash', 'bosbessen', 'peer', 'sinaasappel', 'pompoen', 'avocado', 'knoflook', 'ui', 'appel', 'limoen', 'bloemkool', 'mango', 'sla', 'citroen', 'aubergine', 'artisjokken', 'pruimen', 'prei', 'bananen', 'papaja']
d["a4a_transport"] = ['varen', 'taxi', 'auto', 'fiets', 'vlot', 'pedaal', 'bus', 'handvat', 'boot', 'vrachtwagen', 'slee', 'tapijt', 'motor', 'trein', 'schip', 'bestelwagen', 'kano', 'raket', 'mast', 'slede', 'fiets']