# -*- coding: utf-8 -*-

d = dict()
d["a4a_animals"] = ['krowa', 'indyk', 'krewetka', 'wilk', 'pantera', 'panda', 'sroka', 'małż', 'kucyk', 'mysz', 'pies', 'koala', 'żaba', 'biedronka', 'goryl', 'lama', 'sęp', 'chomik', 'ptak', 'rozgwiazda', 'kruk', 'papuga', 'gąsienica', 'tygrys', 'koliber', 'pirania', 'świnia', 'skorpion', 'lis', 'lampart', 'iguana', 'delfin', 'nietoperz', 'kurczątko', 'krab', 'kura', 'osa', 'kameleon', 'wieloryb', 'jeż', 'jelonek', 'łoś', 'pszczoła', 'żmija', 'dzierzba', 'osioł', 'świnka morska', 'leniwiec', 'koń', 'pingwin', 'wydra', 'niedźwiedź', 'zebra', 'struś', 'wielbłąd', 'antylopa', 'lemur', 'gołąb', 'lama', 'kret', 'płaszczka', 'baran', 'skunks', 'meduza', 'owca', 'rekin', 'kot', 'jeleń', 'ślimak', 'fleming', 'królik', 'ostryga', 'bóbr', 'wróbel', 'gołąb', 'orzeł', 'chrząszcz', 'hipopotam', 'sowa', 'kobra', 'salamandra', 'gęś', 'kangur', 'ważka', 'ropucha', 'pelikan', 'kalmar', 'lwiątko', 'jaguar', 'kaczka', 'jaszczurka', 'nosorożec', 'hiena', 'wół', 'paw', 'papuga', 'łoś', 'aligator', 'mrówka', 'koza', 'króliczek', 'lew', 'wiewiórka', 'opos', 'szympans', 'sarenka', 'goffer', 'słoń', 'żyrafa', 'pająk', 'szczeniak', 'sójka', 'foka', 'kogut', 'żółw', 'byk', 'kot', 'szczur', 'ślimak', 'bawół', 'kos', 'łabędź', 'homar', 'pies', 'komar', 'wąż', 'kurczak', 'mrówkojad']
d["a4a_sport"] = ['judo', 'basen', 'jazda na rowerze', 'rozciąganie', 'kask', 'łyżwy', 'spacer', 'bieg', 'pływanie', 'skakanie na trampolinie', 'wędrówka', 'boks', 'hokej', 'wyścig', 'rzucać', 'jazda na deskorolce', 'wygrywać', 'przysiady', 'narciarstwo', 'golf', 'gwizdek', 'pochodnia', 'żeglarstwo', 'stanie', 'tenis', 'skok', 'wioślarstwo', 'bieg', 'skakanka']
d["a4a_body"] = ['zęby', 'policzek', 'kostka', 'kolano', 'palec u nogi', 'mięsień', 'usta', 'stopy', 'dłoń', 'łokieć', 'włosy', 'rzęsy', 'broda', 'pępek', 'kciuk', 'piersi', 'dziórka w nosie', 'nos', 'biodro', 'ręka', 'brwi', 'pięść', 'szyja', 'nadgarstek', 'gardło ', 'oko', 'noga', 'kręgosłup', 'ucho', 'palec', 'stopa', 'warkocz', 'twarz', 'plecy', 'podbródek', 'tyłek', 'udo', 'brzuch']
d["a4a_people"] = ['dziewczyna', 'chłopiec', 'syn', 'koledzy', 'przyjaciele', 'niemowle', 'dziecko', 'tata', 'mama', 'bliźnięta', 'bracia', 'mężczyzna', 'matka', 'dziadek', 'rodzina', 'dziewczyna', 'żona', 'mąż', 'panna młoda', 'pani', 'babcia', 'para', 'chłopak', 'bliźniaczki', 'plemię', 'chłopak', 'siostry', 'kobieta', 'pani']
d["a4a_food"] = ['słodycze', 'kiełbasa', 'hamburger', 'stek', 'krówka', 'pączek', 'kokos', 'ryż', 'lód', 'galaretka', 'jogurt', 'deser', 'precel', 'orzeszek ziemny', 'dżem', 'uczta', 'ciasteczko', 'boczek', 'przyprawy', 'kawa', 'ciasto', 'lemoniada', 'czekolada', 'butelka wody', 'lunch', 'lód', 'cukier', 'sos', 'zupa', 'sok', 'frytki', 'ciasto', 'ziemniaki puree', 'herbata', 'bułka', 'ser', 'wołowina', 'kanapka', 'plasterki', 'posypka', 'pizza', 'mąka', 'guma do żucia', 'spaghetti', 'pieczeń', 'gulasz', 'smarować', 'mięso ', 'mleko', 'objad', 'kukurydza', 'chleb', 'orzech włoski', 'jajko', 'hot dog', 'szynka']
d["a4a_clothes_n_accessories"] = ['biżuteria', 'skarpetka', 'kurtka', 'obcas', 'kitel', 'shorty', 'kieszeń', 'naszyjnik', 'bluza', 'mundur', 'płaszcz przeciwdeszczowy', 'spodnie', 'okulary przeciwsłoneczne', 'płaszcz', 'sweter', 'koszula', 'sandały', 'garnitur', 'piżama', 'spódnica', 'zamek błyskawiczny', 'buty', 'klejnot', 'krawat', 'pantofle', 'rękawiczki', 'kapelusz', 'rękaw', 'czapka', 'strój kąpielowy', 'but sportowy', 'kamizelka', 'okulary', 'sznurówka', 'łata', 'szalik', 'but', 'guzik', 'sukienka', 'szarfa', 'podeszwa buta', 'szata', 'spodenki', 'kimono', 'spodnie na szelkach']
d["a4a_actions"] = ['lizać', 'rzucać', 'żebrać', 'spadać', 'drapać', 'dotykać', 'wąchać', 'patrzeć', 'wspinać się', 'kopać', 'wyć', 'spać', 'zwiedzać', 'rysować', 'przytulić', 'uczyć się', 'drzemać', 'lepić z gliny', 'łowić', 'klepnąć', 'płakać', 'śpiewać', 'spotkać', 'sprzedawać', 'dziobać', 'oberwać', 'uklęknąć', 'znaleźć', 'tańczyć', 'kaszleć', 'uciąć', 'myśleć', 'szczekać', 'mówić', 'dopingować', 'piec', 'pisać', 'uderzyć', 'brzdąkać', 'uczyć się', 'orać', 'marzyć', 'wysyłać', 'nurkować', 'szeptać', 'szlochać', 'potrząsnąć', 'nakarmić', 'raczkować', 'biwakować', 'rozlać', 'myć się', 'krzyczeć', 'rozerwać', 'unosić się', 'ciągnąć', 'zjeść', 'pocałować', 'siedzieć', 'wykluwać się', 'puścić oczko', 'słyszeć', 'pocałować', 'bawić się', 'kąpać się', 'rozmawiać', 'jeździć', 'pić', 'latać', 'żonglować', 'ugryźć', 'zamiatać', 'patrzeć', 'robić na drutach', 'podnieść', 'przynieść', 'czytać', 'rechotać', 'gapić się', 'jeść']
d["a4a_construction"] = ['latarnia morska', 'drzwi', 'cyrk', 'kościół', 'buda', 'świątynia', 'dym', 'komin', 'cegła', 'studnia', 'ulica', 'zamek', 'sklep', 'schody', 'szkoła', 'gospodarstwo', 'most', 'tama', 'piramida', 'stodoła', 'młyn', 'okno', 'szopa', 'schód', 'sklep', 'szopa', 'dach', 'wieża', 'garaż', 'meczet', 'szpital', 'namiot', 'dom', 'ściana', 'bank', 'okiennica', 'szałas']
d["a4a_nature"] = ['ziemia', 'klif', 'wzgórze', 'kanion', 'skała', 'morze', 'jezioro', 'wybrzeże', 'plaża', 'góra', 'staw', 'szczyt', 'lawa', 'jaskinia', 'wydma', 'wyspa', 'las', 'pustynia', 'góra lodowa']
d["a4a_jobs"] = ['klaun', 'inżynier', 'ksiądz', 'weterynarz', 'sędzia', 'szef kuchni', 'sportowiec', 'bibliotekarka', 'żongler', 'policjant', 'hydraulik', 'medal', 'królowa', 'rolnik', 'magik', 'rycerz', 'lekarz', 'murarz', 'sprzątaczka', 'nauczyciel', 'myśliwy', 'żołnierz', 'muzyk', 'prawnik', 'wędkarz', 'księżniczka', 'strażak', 'zakonnica', 'pirat', 'kowboj', 'elektryk', 'pielęgniarka', 'król', 'prezydent', 'pracownik biurowy', 'stolarz', 'dżokej', 'pracownik', 'mechanik', 'pilot', 'aktor', 'kucharz', 'student', 'rzeźnik', 'księgowy', 'książę', 'papież', 'marynarz', 'bokser', 'baletnica', 'trener', 'astronauta', 'malarz', 'anestezjolog', 'naukowiec']
d["a4a_fruit_n_veg"] = ['marchew', 'jeżyny', 'seler', 'rzepa', 'kakao', 'brzoskwinia', 'melon', 'grejpfrut', 'brokuła', 'winogrona', 'szpinak', 'figa', 'pestka', 'rzodkiewka', 'pomidor', 'kiwi', 'szparagi', 'oliwki', 'ogórki', 'fasola', 'truskawka', 'papryka', 'malina', 'morela', 'ziemniaki', 'groszek', 'kapusta', 'wiśnie', 'dynia', 'jagody', 'gruszka', 'pomarańcza', 'dynia', 'awokado', 'czosnek', 'cebula', 'jabłko', 'limonka', 'kalafior', 'mango', 'sałata', 'cytryna', 'bakłażan', 'karczochy', 'śliwki', 'por', 'banany', 'papaja']
d["a4a_transport"] = ['żagiel', 'taksówka', 'samochód', 'rower', 'tratwa', 'pedał', 'autobus', 'kierownica', 'łódka', 'ciężarówka', 'sanie', 'latający dywan', 'motocykl', 'pociąg', 'statek', 'van', 'kajak', 'rakieta', 'maszt', 'sanki', 'rower']