# -*- coding: utf-8 -*-

d = dict()
d["a4a_animals"] = ['vaca', '<turkey>', 'camarão', '<wolf>', '<panther>', '<panda>', '<magpie>', 'molusco', '<pony>', '<mouse>', 'pug', '<koala>', 'sapo', '<ladybug>', '<gorilla>', '<llama>', '<vulture>', '<hamster>', 'pássaro', 'estrela do mar', 'corvo', '<parakeet>', '<caterpillar>', '<tiger>', '<hummingbird>', '<piranha>', 'porco', '<scorpion>', 'raposa', '<leopard>', '<iguana>', '<dolphin>', 'morcego', 'pintinho', 'caranguejo', 'galinha', '<wasp>', '<chameleon>', '<whale>', '<hedgehog>', '<fawn>', '<moose>', 'abelha', '<viper>', '<shrike>', '<donkey>', '<guinea pig>', '<sloth>', '<horse>', '<penguin>', '<otter>', '<bear>', '<zebra>', '<ostrich>', 'camelo', '<antelope>', '<lemur>', '<pigeon>', '<lama>', 'toupeira', '<ray>', '<ram>', 'gambá', '<jellyfish>', '<sheep>', 'tubarão', '<kitten>', '<deer>', 'caracol', '<flamingo>', '<rabbit>', '<oyster>', '<beaver>', '<sparrow>', '<dove>', '<eagle>', 'besouro', '<hippopotamus>', 'coruja', '<cobra>', '<salamander>', '<goose>', '<kangaroo>', '<dragonfly>', '<toad>', '<pelican>', 'lula', '<lion cub>', '<jaguar>', 'pato', '<lizard>', '<rhinoceros>', '<hyena>', 'boi', '<peacock>', '<parrot>', '<elk>', 'jacaré', '<ant>', 'cabra', '<baby rabbit>', '<lion>', 'esquilo', '<opossum>', 'chimpanzé', '<doe>', '<gopher>', '<elephant>', 'girafa', 'aranha', 'cachorro', '<jay>', '<seal>', '<rooster>', '<turtle>', '<bull>', 'gato', 'rato', '<slug>', '<buffalo>', '<blackbird>', 'cisne', '<lobster>', 'cachorro', 'mosquito', 'cobra', 'frango', '<anteater>']
d["a4a_sport"] = ['<judo>', 'piscina', 'pedalar', 'alongar', '<helmet>', '<ice skating>', 'andar', 'correr', 'nadar', 'saltar', 'caminhar', '<boxing>', '<hockey>', '<race>', 'arremessar', 'patinar', 'ganhar', 'agachar', 'esquiar', '<golf>', '<whistle>', 'tocha', '<sailing>', 'de pé', '<tennis>', 'pular', '<rowing>', 'correr', 'corda']
d["a4a_body"] = ['dentes', '<cheek>', '<ankle>', 'joelho', '<toe>', '<muscle>', 'boca', '<feet>', 'mão', '<elbow>', 'cabelo', '<eyelash>', '<beard>', '<belly button>', '<thumb>', '<breast>', '<nostril>', 'nariz', 'quadril', '<arm>', '<eyebrow>', 'punho', 'pescoço', 'pulso', 'garganta', '<eye>', '<leg>', '<spine>', 'orelha', '<finger>', 'pé', 'trança', 'rosto', 'costas', 'queixo', '<bottom>', 'coxa', '<belly>']
d["a4a_people"] = ['menina', '<male>', '<son>', '<mates>', '<friends>', '<baby>', 'criança', 'pai', '<mom>', '<twin boys>', '<brothers>', '<man>', '<mother>', '<grandfather>', '<family>', '<female>', '<wife>', '<husband>', 'noiva', '<madam>', '<grandmother>', '<couple>', 'rapaz', '<twin girls>', '<tribe>', 'menino', '<sisters>', '<woman>', '<lady>']
d["a4a_food"] = ['doce', '<sausage>', '<hamburger>', '<steak>', 'doce de chocolate', '<doughnut>', '<coconut>', 'arroz', '<ice cream>', '<jelly>', '<yoghurt>', '<dessert>', '<pretzel>', '<peanut>', '<jam>', 'banquete', 'biscoito', '<bacon>', '<spice>', '<coffee>', '<pie>', '<lemonade>', 'chocolate', '<water bottle>', 'lanche', 'gelo', '<sugar>', 'molho', '<soup>', 'suco', '<fries>', 'bolo', '<mashed potatoes>', '<tea>', 'brioche', 'queijo', '<beef>', 'sanduíche', '<slice>', 'granulado', '<pizza>', 'farinha', 'chiclete', 'espaguete', '<roast>', 'ensopado', 'espalhar', '<meat>', '<milk>', '<meal>', 'milho', 'pão', '<walnut>', '<egg>', '<hot dog>', '<ham>']
d["a4a_clothes_n_accessories"] = ['<jewellery>', 'meia', '<jacket>', '<heel>', 'jaleco', '<shorts>', '<pocket>', '<necklace>', '<sweatshirt>', '<uniform>', '<raincoat>', '<trousers>', '<sunglasses>', 'casaco', '<pullover>', 'camisa', '<sandals>', 'terno', '<pyjamas>', 'saia', '<zip>', '<shoes>', 'jóia', '<tie>', '<slippers>', '<gloves>', 'chapéu', 'manga', 'boné', '<swimming suit>', '<trainer>', '<vest>', '<glasses>', '<shoelace>', 'remendo', 'cachecol', 'sapato', '<button>', 'vestido', '<sash>', '<shoe sole>', '<robe>', '<pants>', '<kimono>', '<overalls>']
d["a4a_actions"] = ['lamber', '<slam>', 'implorar', '<fell>', 'arranhar', 'tocar', 'farejar', 'observar', 'escalar', 'escavar', 'uivar', 'dormir', 'explorar', 'desenhar', 'abraçar', 'ensinar', 'cochilar', 'argila', 'pegar', 'palma', 'chorar', 'cantar', 'encontrar', '<sell>', 'bicar', '<beat>', 'ajoelhar', 'encontrar', 'dança', '<cough>', 'cortar', 'pensar', 'latir', '<speak>', 'torcer', '<bake>', 'escrever', '<punch>', '<strum>', 'estudar', 'arar', 'sonhar', '<post>', 'mergulho', 'cochichar', '<sob>', 'sacudir', '<feed>', 'engatinhar', 'acampamento', 'derramar', 'limpar', 'gritar', 'rasgar', 'boiar', '<pull>', '<ate>', '<kiss>', 'sentar', 'chocar', 'piscar', 'escutar', 'beijar', 'brincar', 'lavar', 'conversar', 'dirigir', 'bebida', 'voar', '<juggle>', 'mordida', '<sweep>', 'olhar', 'tricotar', 'levantar', 'buscar', 'ler', 'coaxar', 'olhar', 'comer']
d["a4a_construction"] = ['<lighthouse>', 'porta', '<circus>', '<church>', '<kennel>', '<temple>', 'fumaça', '<chimney>', 'tijolo', '<well>', 'rua', 'castelo', 'mercearia', '<staircase>', 'escola', 'fazenda', 'ponte', '<dam>', '<pyramid>', 'celeiro', '<mill>', '<window>', 'cabana', '<step>', 'loja', 'celeiro', 'telhado', '<steeple>', '<garage>', '<mosque>', '<hospital>', '<tent>', '<house>', '<wall>', 'banco', '<shutter>', 'oca']
d["a4a_nature"] = ['terreno', 'penhasco', '<hill>', '<canyon>', 'rocha', '<sea>', 'lago', '<coast>', 'costa', '<mountain>', '<pond>', '<peak>', '<lava>', 'caverna', 'duna', '<island>', '<forest>', '<desert>', '<iceberg>']
d["a4a_jobs"] = ['palhaço', '<engineer>', '<priest>', 'veterinário', 'juiz', '<chef>', 'atleta', '<librarian>', '<juggler>', '<policeman>', '<plumber>', 'insígnia', 'rainha', '<farmer>', '<magician>', 'cavaleiro', '<doctor>', '<bricklayer>', '<cleaner>', 'professor', 'caçador', '<soldier>', '<musician>', '<lawyer>', '<fisherman>', 'princesa', '<fireman>', '<nun>', '<pirate>', 'vaqueiro', '<electrician>', '<nurse>', '<king>', '<president>', '<office worker>', '<carpenter>', '<jockey>', '<worker>', '<mechanic>', '<pilot>', '<actor>', 'cozinhar', '<student>', '<butcher>', '<accountant>', 'príncipe', 'papa', '<sailor>', '<boxer>', '<ballet dancer>', 'treinador', '<astronaut>', '<painter>', '<anaesthesiologist>', '<scientist>']
d["a4a_fruit_n_veg"] = ['cenoura', '<blackberries>', '<celery>', '<turnip>', '<cacao>', 'pêssego', '<melon>', '<grapefruit>', '<broccoli>', '<grapes>', '<spinach>', '<fig>', '<kernel>', '<radish>', '<tomato>', '<kiwi>', '<asparagus>', '<olives>', '<cucumbers>', '<beans>', 'morango', '<peppers>', '<raspberry>', '<apricot>', '<potatoes>', '<peas>', '<cabbage>', '<cherries>', 'abóbora', '<blueberries>', '<pear>', 'laranja', '<pumpkin>', '<avocado>', '<garlic>', '<onion>', '<apple>', 'limão', '<cauliflower>', '<mango>', '<lettuce>', '<lemon>', '<aubergine>', '<artichokes>', '<plums>', '<leek>', '<bananas>', '<papaya>']
d["a4a_transport"] = ['veleiro', '<taxi>', 'carro', 'bicicleta', '<raft>', '<pedal>', '<bus>', '<handlebar>', 'barco', 'caminhão', 'trenó', '<carpet>', '<motorcycle>', 'trem', 'navio', 'van', 'canoa', '<rocket>', '<mast>', '<sledge>', '<bicycle>']