# -*- coding: utf-8 -*-

d = dict()
d["a4a_animals"] = ['vaca', 'peru', 'camarão', 'lobo', 'pantera', 'panda', 'pega', 'amêijoa', 'pónei', 'rato', 'buldogue', 'coala', 'sapo', 'joaninha', 'gorila', '<llama>', 'vulto', '<hamster>', 'pássaro', 'estrela-do-mar', 'corvo', 'periquito', 'lagarta', 'tigre', 'beija-flor', 'piranha', 'porco', 'escorpião', 'raposa', 'leopardo', 'iguana', 'golfinho', 'morcego', 'passarinho', 'caranguejo', 'galinha', 'vespa', 'camaleão', 'baleia', 'ouriço', 'gamo', 'alce', 'abelha', 'víbora', '<shrike>', '<donkey>', '<guinea pig>', 'preguiça', 'cavalo', '<penguin>', 'lontra', 'urso', 'zebra', 'avestruz', 'camelo', 'antílope', 'lémur', 'pardal', 'lama', 'toupeira', '<ray>', '<ram>', 'doninha', 'medusa', 'ovelha', 'tubarão', 'gatinho', 'veado', 'caracol', 'flamingo', 'coelho', 'ostra', 'castor', 'pardal', 'pomba', 'águia', 'escaravelho', 'hipopótamo', 'coruja', 'cobra', 'salamandra', 'ganso', 'canguru', 'libélula', 'sapo', 'pelicano', 'lula', '<lion cub>', 'jaguar', 'pato', 'lagarto', 'rinoceronte', 'hiena', 'boi', 'pavão', 'papagaio', 'alce', 'crocodilo', 'formiga', 'cabra', '<baby rabbit>', 'leão', 'esquilo', 'gambá', 'chimpanzé', 'fêmea', '<gopher>', '<elephant>', 'girafa', 'aranha', 'cãozinho', 'gaio', '<seal>', '<rooster>', 'tartaruga', 'touro', 'gato', 'rato', 'lesma', 'búfalo', 'melro', 'cisne', 'lagosta', 'cão', 'mosquito', 'cobra', 'galinha', 'papa-formigas']
d["a4a_sport"] = ['judo', 'piscina', 'montar', 'esticar', 'capacete', '<ice skating>', 'andar', 'correr', 'nadar', 'salto', 'caminhar', '<boxing>', 'hóquei', 'corrida', 'lançar', 'skate', 'vencer', 'agachar', 'esqui', 'golfe', '<whistle>', 'tocha', '<sailing>', 'garagem', 'ténis', 'saltar', 'remar', 'correr', 'corda']
d["a4a_body"] = ['dentes', 'bochecha', 'tornozelo', 'joelho', 'unha', 'músculo', 'boca', '<feet>', 'mão', 'ombro', 'cabelo', 'pestanas', 'barba', '<belly button>', 'polegar', 'peito', 'narina', 'nariz', 'anca', 'braço', '<eyebrow>', 'punho', 'pescoço', 'pulso', 'garganta', '<eye>', 'perna', 'espinha', 'orelha', 'dedo', 'pé', 'trança', 'cara', 'costas', 'queixo', 'fundo', 'coxa', 'barriga']
d["a4a_people"] = ['menina', '<male>', 'filho', '<mates>', '<friends>', '<baby>', 'filho', 'pai', 'mamã', '<twin boys>', '<brothers>', 'homem', 'mãe', '<grandfather>', 'família', '<female>', 'esposa', 'marido', 'noiva', '<madam>', 'avó', 'casal', 'rapaz', '<twin girls>', 'tribo', 'rapaz', '<sisters>', 'mulher', 'senhora']
d["a4a_food"] = ['doce', 'salsicha', 'hambúrguer', '<steak>', 'doce de leite', 'donut', 'coco', 'arroz', '<ice cream>', 'geleia', '<yoghurt>', 'sobremesa', '<pretzel>', '<peanut>', 'compota', 'festejo', 'biscoito', '<bacon>', 'especiaria', 'café', 'tarte', 'limonada', 'chocolate', '<water bottle>', 'almoço', 'gelo', 'açúcar', 'molho', 'sopa', 'sumo', 'fritos', 'bolo', '<mashed potatoes>', '<tea>', 'brioche', 'queijo', '<beef>', 'sanduíche', '<slice>', 'pepitas', 'pizza', 'farinha', 'goma', 'esparguete', 'assado', 'estufado', 'espalhar', 'carne', 'leite', 'refeição', 'milho', 'pão', 'noz', 'ovo', '<hot dog>', 'fiambre']
d["a4a_clothes_n_accessories"] = ['<jewellery>', 'meia', 'casaco', 'palma', 'bata', '<shorts>', 'bolso', 'colar', 'camisola', 'uniforme', 'impermeável', '<trousers>', '<sunglasses>', 'casaco', 'pulover', 'camisa', 'sandálias', 'fato', '<pyjamas>', 'saia', '<zip>', '<shoes>', 'jóia', '<tie>', 'chinelo', '<gloves>', 'chapéu', 'manga', 'boné', '<swimming suit>', '<trainer>', 'veste', 'óculos', 'atacador', 'remendo', 'cachecol', 'sapato', 'botão', 'vestido', 'banda', '<shoe sole>', 'roupão', 'calças', 'quimono', '<overalls>']
d["a4a_actions"] = ['lamber', 'bater a porta', 'pedir', '<fell>', 'coçar', 'tocar', 'cheirar', 'ver', 'trepar', 'cavar', 'uivar', 'dormir', 'explorar', 'desenhar', 'abraçar', 'ensinar', 'descansar', 'barro', 'apanhar', 'bater palmas', 'chorar', 'cantar', 'encontrar', '<sell>', 'bicar', 'bater', 'ajoelhar', 'procurar', 'dançar', 'tossir', 'cortar', 'pensar', 'ladrar', 'falar', 'animar', '<bake>', 'escrever', '<punch>', '<strum>', 'estudar', 'arar', 'sonhar', 'poste', 'mergulhar', 'sussurrar', 'choro', 'agitar', 'alimentar', 'arrastar', 'campo', 'entornar', 'limpar', 'gritar', 'separar', 'flutuar', 'puxar', '<ate>', 'beijar', 'sentar', 'chocar', 'piscar', 'ouvir', 'beijocar', 'jogar', 'lavar', 'conversar', 'conduzir', 'bebida', 'voar', '<juggle>', 'bit', '<sweep>', 'olhar', 'tricotar', 'levantamento', 'apanhar', 'ler', 'coaxar', 'mirar', 'comer']
d["a4a_construction"] = ['farol', 'porta', 'circo', '<church>', '<kennel>', 'templo', 'fumo', 'chaminé', 'tijolo', '<well>', 'rua', 'castelo', 'loja', 'escadaria', 'escola', 'quinta', 'ponte', 'barragem', 'pirâmide', 'celeiro', 'moinho', 'janela', 'cabana', 'degrau', 'loja', 'estábulo', 'tecto', 'torre', 'garagem', 'mesquita', 'hospital', 'tenda', 'casa', 'parede', 'banco', 'persiana', 'cabana']
d["a4a_nature"] = ['terra', 'penhasco', 'colina', 'penhasco', 'rocha', 'mar', 'lago', 'costa', 'beira-mar', 'montanha', 'charco', 'pico', 'lava', 'gruta', 'duna', 'ilha', 'floresta', 'deserto', 'icebergue']
d["a4a_jobs"] = ['palhaço', 'engenheiro', 'padre', 'veterinário', 'juiz', 'cozinheiro', 'atleta', 'bibliotecário', 'malabarista', '<policeman>', 'canalizador', 'medalha', 'rainha', 'agricultor', '<magician>', 'cavaleiro', 'médico', 'pedreiro', '<cleaner>', 'professor', 'caçador', 'soldado', 'músico', 'advogado', 'pescador', 'princesa', 'bombeiro', 'freira', 'pirata', 'cowboy', 'electricista', 'enfermeira', 'rei', 'presidente', '<office worker>', 'carpinteiro', 'cavaleiro', 'funcionário', 'mecânico', 'piloto', 'actor', 'cozinhar', 'estudante', 'talhante', 'contabilista', 'príncipe', 'papa', 'marinheiro', 'pugilista', '<ballet dancer>', 'treinador', 'astronauta', '<painter>', '<anaesthesiologist>', '<scientist>']
d["a4a_fruit_n_veg"] = ['cenoura', '<blackberries>', 'aipo', 'nabo', 'cacau', 'pêssego', 'melão', 'toranja', 'brócolo', '<grapes>', 'espinafre', 'figo', 'caroço', 'rabanete', '<tomato>', 'kiwi', 'espargo', '<olives>', '<cucumbers>', '<beans>', 'morango', 'pimentos', 'framboesa', 'alperce', '<potatoes>', '<peas>', 'repolho', '<cherries>', 'aboborinha', '<blueberries>', 'pêra', 'laranja', 'abóbora', 'abacate', 'alho', 'cebola', 'maçã', 'lima', 'couve-flor', 'manga', 'alface', 'limão', '<aubergine>', '<artichokes>', '<plums>', 'alho-francês', '<bananas>', 'papaia']
d["a4a_transport"] = ['vela', 'táxi', 'carro', 'bicicleta', 'maçaneta', 'pedal', 'autocarro', 'pega', 'barco', 'camião', 'trenó', 'carpete', 'mota', 'comboio', 'barco', 'carrinha', 'canoa', 'foguete', 'mastro', '<sledge>', '<bicycle>']
