# -*- coding: utf-8 -*-

d = dict()


d["a4a_animals"] = ['vaca', 'peru', 'camarão', 'lobo', 'pantera', 'panda', 'pega', 'amêijoa', 'pónei', 'rato', 'buldogue', 'coala', 'sapo', 'joaninha', 'gorila', 'lama', 'vulto', 'hamster', 'pássaro', 'estrela-do-mar', 'corvo', 'periquito', 'lagarta', 'tigre', 'beija-flor', 'piranha', 'porco', 'escorpião', 'raposa', 'leopardo', 'iguana', 'golfinho', 'morcego', 'passarinho', 'caranguejo', 'galinha', 'vespa', 'camaleão', 'baleia', 'ouriço', 'gamo', 'alce', 'abelha', 'víbora', 'picanço', 'burro', 'porquinho-da-índia', 'preguiça', 'cavalo', 'pinguim', 'lontra', 'urso', 'zebra', 'avestruz', 'camelo', 'antílope', 'lémur', 'pardal', 'lama', 'toupeira', 'raia', 'carneiro', 'doninha', 'medusa', 'ovelha', 'tubarão', 'gatinho', 'veado', 'caracol', 'flamingo', 'coelho', 'ostra', 'castor', 'pardal', 'pomba', 'águia', 'escaravelho', 'hipopótamo', 'coruja', 'cobra', 'salamandra', 'ganso', 'canguru', 'libélula', 'sapo', 'pelicano', 'lula', 'leãozinho', 'jaguar', 'pato', 'lagarto', 'rinoceronte', 'hiena', 'boi', 'pavão', 'papagaio', 'alce', 'crocodilo', 'formiga', 'cabra', 'coelhinho', 'leão', 'esquilo', 'gambá', 'chimpanzé', 'fêmea', 'tuco-tuco', 'elefante', 'girafa', 'aranha', 'cãozinho', 'gaio', 'foca', 'galo', 'tartaruga', 'touro', 'gato', 'rato', 'lesma', 'búfalo', 'melro', 'cisne', 'lagosta', 'cão', 'mosquito', 'cobra', 'galinha', 'papa-formigas']
d["a4a_sport"] = ['judo', 'piscina', 'montar', 'esticar', 'capacete', 'patinagem no gelo', 'andar', 'correr', 'nadar', 'salto', 'caminhar', 'boxe', 'hóquei', 'corrida', 'lançar', 'skate', 'vencer', 'agachar', 'esqui', 'golfe', 'apito', 'tocha', 'vela', 'garagem', 'ténis', 'saltar', 'remar', 'correr', 'corda']
d["a4a_body"] = ['dentes', 'bochecha', 'tornozelo', 'joelho', 'unha', 'músculo', 'boca', 'pé', 'mão', 'ombro', 'cabelo', 'pestanas', 'barba', 'umbigo', 'polegar', 'peito', 'narina', 'nariz', 'anca', 'braço', 'sobrancelha', 'punho', 'pescoço', 'pulso', 'garganta', 'olho', 'perna', 'espinha', 'orelha', 'dedo', 'pé', 'trança', 'cara', 'costas', 'queixo', 'fundo', 'coxa', 'barriga']
d["a4a_people"] = ['menina', 'masculino', 'filho', 'companheiros', 'amigos', 'bebé', 'filho', 'pai', 'mamã', 'rapazes gémeos', 'irmãos', 'homem', 'mãe', 'avô', 'família', 'femenino', 'esposa', 'marido', 'noiva', 'madame', 'avó', 'casal', 'rapaz', 'raparigas gémeas', 'tribo', 'rapaz', 'irmãs', 'mulher', 'senhora']
d["a4a_food"] = ['doce', 'salsicha', 'hambúrguer', 'bife', 'doce de leite', 'donut', 'coco', 'arroz', 'gelado', 'geleia', 'iogurte', 'sobremesa', 'pretzel', 'amendoins', 'compota', 'festejo', 'biscoito', 'bacon', 'especiaria', 'café', 'tarte', 'limonada', 'chocolate', 'garrafa de água', 'almoço', 'gelo', 'açúcar', 'molho', 'sopa', 'sumo', 'fritos', 'bolo', 'puré de batata', 'chá', 'brioche', 'queijo', 'carne de vaca', 'sanduíche', 'fatia', 'pepitas', 'pizza', 'farinha', 'goma', 'esparguete', 'assado', 'estufado', 'espalhar', 'carne', 'leite', 'refeição', 'milho', 'pão', 'noz', 'ovo', 'cachorro-quente', 'fiambre']
d["a4a_clothes_n_accessories"] = ['joias', 'meia', 'casaco', 'palma', 'bata', 'calções', 'bolso', 'colar', 'camisola', 'uniforme', 'impermeável', 'calças', 'óculos de sol', 'casaco', 'pulover', 'camisa', 'sandálias', 'fato', 'pijama', 'saia', 'fecho éclair', 'sapatos', 'jóia', 'gravata', 'chinelo', 'luvas', 'chapéu', 'manga', 'boné', 'fato de banho', 'ténis', 'veste', 'óculos', 'atacador', 'remendo', 'cachecol', 'sapato', 'botão', 'vestido', 'banda', 'sola do sapato', 'roupão', 'calças', 'quimono', 'fato-macaco']
d["a4a_actions"] = ['lamber', 'bater a porta', 'pedir', 'caiu', 'coçar', 'tocar', 'cheirar', 'ver', 'trepar', 'cavar', 'uivar', 'dormir', 'explorar', 'desenhar', 'abraçar', 'ensinar', 'descansar', 'barro', 'apanhar', 'bater palmas', 'chorar', 'cantar', 'encontrar', 'vender', 'bicar', 'bater', 'ajoelhar', 'procurar', 'dançar', 'tossir', 'cortar', 'pensar', 'ladrar', 'falar', 'animar', 'assar', 'escrever', 'soco', 'dedilhar', 'estudar', 'arar', 'sonhar', 'poste', 'mergulhar', 'sussurrar', 'choro', 'agitar', 'alimentar', 'arrastar', 'campo', 'entornar', 'limpar', 'gritar', 'separar', 'flutuar', 'puxar', 'comeu', 'beijar', 'sentar', 'chocar', 'piscar', 'ouvir', 'beijocar', 'jogar', 'lavar', 'conversar', 'conduzir', 'bebida', 'voar', 'fazer malabarismos', 'bit', 'varrer', 'olhar', 'tricotar', 'levantamento', 'apanhar', 'ler', 'coaxar', 'mirar', 'comer']
d["a4a_construction"] = ['farol', 'porta', 'circo', 'igreja', 'canil', 'templo', 'fumo', 'chaminé', 'tijolo', 'poço', 'rua', 'castelo', 'loja', 'escadaria', 'escola', 'quinta', 'ponte', 'barragem', 'pirâmide', 'celeiro', 'moinho', 'janela', 'cabana', 'degrau', 'loja', 'estábulo', 'tecto', 'torre', 'garagem', 'mesquita', 'hospital', 'tenda', 'casa', 'parede', 'banco', 'persiana', 'cabana']
d["a4a_nature"] = ['terra', 'penhasco', 'colina', 'penhasco', 'rocha', 'mar', 'lago', 'costa', 'beira-mar', 'montanha', 'charco', 'pico', 'lava', 'gruta', 'duna', 'ilha', 'floresta', 'deserto', 'icebergue']
d["a4a_jobs"] = ['palhaço', 'engenheiro', 'padre', 'veterinário', 'juiz', 'cozinheiro', 'atleta', 'bibliotecário', 'malabarista', 'polícia', 'canalizador', 'medalha', 'rainha', 'agricultor', 'mágico', 'cavaleiro', 'médico', 'pedreiro', 'limpador', 'professor', 'caçador', 'soldado', 'músico', 'advogado', 'pescador', 'princesa', 'bombeiro', 'freira', 'pirata', 'cowboy', 'electricista', 'enfermeira', 'rei', 'presidente', 'empregado de escritório', 'carpinteiro', 'cavaleiro', 'funcionário', 'mecânico', 'piloto', 'actor', 'cozinhar', 'estudante', 'talhante', 'contabilista', 'príncipe', 'papa', 'marinheiro', 'pugilista', 'bailarina', 'treinador', 'astronauta', 'pintor', 'anestesiologista', 'cientista']
d["a4a_fruit_n_veg"] = ['cenoura', 'amoras', 'aipo', 'nabo', 'cacau', 'pêssego', 'melão', 'toranja', 'brócolo', 'uvas', 'espinafre', 'figo', 'caroço', 'rabanete', 'tomate', 'kiwi', 'espargo', 'azeitonas', 'pepinos', 'feijão', 'morango', 'pimentos', 'framboesa', 'alperce', 'batatas', 'ervilhas', 'repolho', 'cerejas', 'aboborinha', 'mirtilos', 'pêra', 'laranja', 'abóbora', 'abacate', 'alho', 'cebola', 'maçã', 'lima', 'couve-flor', 'manga', 'alface', 'limão', 'beringela', 'alcachofras', 'ameixas', 'alho-francês', 'bananas', 'papaia']
d["a4a_transport"] = ['vela', 'táxi', 'carro', 'bicicleta', 'maçaneta', 'pedal', 'autocarro', 'pega', 'barco', 'camião', 'trenó', 'carpete', 'mota', 'comboio', 'barco', 'carrinha', 'canoa', 'foguete', 'mastro', 'trenó', 'bicicleta']