# -*- coding: utf-8 -*-

d = dict()


d["a4a_animals"] = ['ko', 'kalkon', 'räka', 'varg', 'panter', 'panda', 'skata', 'mussla', 'ponny', 'mus', 'mops', 'koala', 'groda', 'nyckelpiga', 'gorilla', 'lama', 'gam', 'hamster', 'fågel', 'sjöstjärna', 'kråka', 'parakit', 'fjärilslarv', 'tiger', 'kolibri', 'piraya', 'gris', 'skorpion', 'räv', 'leopard', 'leguan', 'delfin', 'fladdermus', 'kyckling', 'krabba', 'höna', 'geting', 'kameleont', 'val', 'igelkott', 'rådjur', 'älg', 'bi', 'huggorm', 'skata', 'åsna', 'marsvin', 'sengångare', 'häst', 'pingvin', 'utter', 'björn', 'zebra', 'struts', 'kamel', 'antilop', 'lemur', 'duva', 'lama', 'mullvad', 'rocka', 'bock', 'skunk', 'manet', 'får', 'haj', 'källing', 'hjort', 'snigel', 'flamingo', 'kanin', 'ostron', 'bäver', 'sparv', 'duva', 'örn', 'skalbagge', 'flodhäst', 'uggla', 'kobra', 'salamander', 'gås', 'känguru', 'trollslända', 'padda', 'pelikan', 'bläckfisk', 'lejonunge', 'jaguar', 'anka', 'ödla', 'noshörning', 'hyena', 'oxe', 'påfågel', 'papegoja', 'vapiti', 'alligator', 'myra', 'get', 'kaninunge', 'lejon', 'ekorre', 'pungdjur', 'schimpans', 'hind', 'kindpåsråtta', 'elefant', 'giraff', 'spindel', 'valp', 'nötskrika', 'säl', 'tupp', 'sköldpadda', 'tjur', 'katt', 'råtta', 'snigel', 'buffel', 'koltrast', 'svan', 'hummer', 'hund', 'mygga', 'orm', 'kyckling', 'myrslok']
d["a4a_sport"] = ['judo', 'pool', 'rida', 'strech', 'hjälm', 'skridskoåkning', 'gå', 'spring', 'simma', 'hopp', 'vandra', 'boxning', 'hockey', 'tävla', 'kasta', 'skridsko', 'vinna', 'knäböj', 'åka skidor', 'golf', 'vissla', 'fackla', 'skeppa', 'stå', 'tennis', 'hoppa', 'rodd', 'jogga', 'rep']
d["a4a_body"] = ['tänder', 'kind', 'ankel', 'knä', 'tå', 'muskel', 'mun', 'fot', 'hand', 'armbåge', 'hår', 'ögonlock', 'skägg', 'navel', 'tumme', 'bröst', 'näsborre', 'näsa', 'höft', 'arm', 'ögonbryn', 'knoge', 'nacke', 'handled', 'hals', 'öga', 'ben', 'ryggrad', 'öra', 'finger', 'fot', 'fläta', 'ansikte', 'rygg', 'haka', 'botten', 'lår', 'buk']
d["a4a_people"] = ['flicka', 'hane', 'son', 'par', 'vänner', 'barn', 'barn', 'pappa', 'mamma', 'tvillingpojkar', 'bröder', 'man', 'moder', 'farfar', 'familj', 'hona', 'fru', 'man', 'brud', 'dam', 'farmor', 'par', 'gosse', 'tvillingflickor', 'stam', 'pojke', 'systrar', 'kvinna', 'dam']
d["a4a_food"] = ['godis', 'korv', 'hamburgare', 'stek', 'mjuk kola', 'munk', 'kokosnöt', 'ris', 'glass', 'gele', 'yoghurt', 'dessert', 'kringla', 'jordnöt', 'sylt', 'festmåltid', 'kaka', 'bacon', 'krydda', 'kaffe', 'paj', 'lemonad', 'choklad', 'vattenflaska', 'lunch', 'is', 'socker', 'sås', 'soppa', 'juice', 'pommes frites', 'kaka', 'potatismos', 'te', 'bulle', 'ost', 'biff', 'macka', 'skiva', 'strö', 'pizza', 'mjöl', 'tandkött', 'spagetti', 'steka', 'gryta', 'sprida', 'kött', 'mjölk', 'målltid', 'majs', 'bröd', 'vallnöt', 'ägg', 'korv', 'skinka']
d["a4a_clothes_n_accessories"] = ['smycken', 'strumpa', 'jacka', 'häl', 'skyddsrock', 'shorts', 'ficka', 'halsband', 'tröja', 'uniform', 'regnjacka', 'byxor', 'solglasögon', 'kappa', 'pullover', 'skjorta', 'sandaler', 'kostym', 'pyjamas', 'kjol', 'stänga', 'skor', 'juvel', 'slips', 'tofflor', 'handskar', 'hat', 'ärm', 'mössa', 'simdräkt', 'tränare', 'väst', 'glasögon', 'skosnöre', 'lapp', 'skarf', 'sko', 'knapp', 'klänning', 'skärp', 'skosula', 'dräkt', 'byxor', 'kimono', 'overall']
d["a4a_actions"] = ['slicka', 'smälla', 'be', 'ramla', 'skrapa', 'nudda', 'lukta', 'se', 'klättra', 'gräva', 'yla', 'sova', 'utforska', 'dra', 'krama', 'lära', 'tupplur', 'lera', 'fånga', 'klappa', 'gråta', 'sjunga', 'träffa', 'sälja', 'picka', 'slå', 'knäböja', 'hitta', 'dansa', 'hosta', 'skära', 'tänka', 'skälla', 'tala', 'heja', 'baka', 'skriva', 'slå', 'knäppa', 'studera', 'ploga', 'drömma', 'posta', 'dyka', 'viska', 'snyfta', 'skaka', 'mata', 'kravla', 'kampa', 'spilla', 'städa', 'skrika', 'tår', 'flyta', 'dra', 'åt', 'kyss', 'sitta', 'kläcka', 'blinka', 'höra', 'pussas', 'spela', 'tvätta', 'chatta', 'köra', 'att dricka', 'flyga', 'jonglera', 'bit', 'svepa', 'se', 'sticka', 'lyfta', 'hämta', 'läsa', 'kväka', 'stirra', 'äta']
d["a4a_construction"] = ['fyr', 'dörr', 'cirkus', 'kyrka', 'kennel', 'tempel', 'rök', 'skorsten', 'tegel', 'brunn', 'gata', 'slott', 'affär', 'trappa', 'skola', 'bondgård', 'bro', 'damm', 'pyramid', 'lada', 'kvarn', 'fönster', 'stuga', 'steg', 'butik', 'skjul', 'task', 'kyrktorn', 'garage', 'moské', 'sjukhus', 'tält', 'hus', 'vägg', 'bank', 'slutare', 'hydda']
d["a4a_nature"] = ['mark', 'klippa', 'kulle', 'kanjon', 'sten', 'hav', 'sjö', 'kust', 'strand', 'berg', 'damm', 'topp', 'lava', 'grotta', 'dyn', 'ö', 'skog', 'öken', 'isberg']
d["a4a_jobs"] = ['clown', 'ingenjör', 'präst', 'vetrinär', 'domare', 'kock', 'atlet', 'bibliotekarie', 'jonglör', 'polis', 'rörmockare', 'bricka', 'drottning', 'bonde', 'magiker', 'riddare', 'doktor', 'murare', 'städare', 'lärare', 'jägare', 'soldat', 'musikant', 'advokat', 'fiskare', 'prinsessa', 'brandman', 'nuna', 'pirat', 'cowboy', 'elektriker', 'sjuksköterska', 'kung', 'president', 'kontorsarbetare', 'snickare', 'jockey', 'arbetare', 'mekaniker', 'pilot', 'skådespelare', 'kock', 'student', 'slaktare', 'ekonom', 'prins', 'påve', 'sjöman', 'boxare', 'ballerina', 'tränare', 'astronaut', 'målare', 'anestesiolog', 'forskare']
d["a4a_fruit_n_veg"] = ['morot', 'björnbär', 'selleri', 'rova', 'kakao', 'persika', 'melon', 'grapefrukt', 'broccoli', 'vindruvor', 'spenat', 'fikon', 'kärna', 'rädisa', 'tomat', 'kiwi', 'sparris', 'oliver', 'gurka', 'bönor', 'jordgubbe', 'paprikor', 'hallon', 'aprikos', 'potatis', 'ärtor', 'kål', 'körsbär', 'squash', 'blåbär', 'päron', 'apelsin', 'pumpa', 'avokado', 'vitlök', 'lök', 'äpple', 'lime', 'blomkål', 'mango', 'sallad', 'citron', 'aubergine', 'kronärtskocka', 'plommon', 'purjolök', 'bananer', 'papaya']
d["a4a_transport"] = ['segel', 'taxi', 'bil', 'cykel', 'flotte', 'pedal', 'buss', 'styre', 'båt', 'lastbil', 'släde', 'matta', 'motorcykel', 'tåg', 'skepp', 'skåpbil', 'kanot', 'raket', 'mast', 'slägga', 'cykel']