# -*- coding: utf-8 -*-

# This is a list of words used by the word builder and word maze games and possibly other games built in the future
# these words are a naive translation of a part of most commonly used words in English in each sub-list in the list di
# first number is a number of words in the sub-list to avoid counting it every time the list is selected the sub-lists
# are consisting of words with len() of 3 - 10. I think the way of going about internationalization here would be to
# create a new list with words most commonly used in your language rather than translating the English version.
# I am not sure if they are appropriate for children, but if anyone is interested we can try to built something more
# suitable or if you like you can try to edit this list - remove the words that you think are either not in German or
# are not suitable for under 10 years old children and send it back to the email address shown at the start of the game.
# If you have a better list please send it to me and I will format it and add it to the game. This is a very naive
# translation from google translate - only resorted and counted.

di = [[13, 'alí', 'até', 'blé', 'bló', 'gmá', 'iná', 'ité', 'ičú', 'mní', 'owá', 'pȟá', 'slá', 'čhó'],
[49, 'apȟá', 'aȟčó', 'hečá', 'igmú', 'ikhú', 'ipȟá', 'istó', 'išpá', 'ištá', 'kaká', 'knit', 'káǧa', 'lamá', 'loté', 'maká', 'mayá', 'maǧá', 'máni', 'máza', 'napé', 'osúŋ', 'othí', 'oáli', 'pahá', 'pope', 'psíŋ', 'ptáŋ', 'pšíŋ', 'sutá', 'sápa', 'uŋzé', 'uŋčí', 'wáta', 'wíta', 'wíši', 'wóla', 'wóta', 'wówa', 'wóžu', 'yúta', 'yúza', 'zičá', 'éthi', 'ógle', 'ómna', 'úŋpi', 'šiná', 'šóka', 'šóta'],
[74, 'atáya', 'ayúta', 'bloká', 'bléla', 'blóza', 'glúza', 'haŋpa', 'haŋpí', 'hoǧáŋ', 'hoȟpá', 'háŋpa', 'húŋku', 'iyéya', 'iǧúǧa', 'iȟála', 'iȟáȟa', 'khiwí', 'khéya', 'lowáŋ', 'mahél', 'makhú', 'makȟá', 'matȟó', 'napsú', 'napȟá', 'nážiŋ', 'núŋǧe', 'ohíya', 'okáǧe', 'ománi', 'oyáte', 'oyúso', 'ošóta', 'ožíži', 'phuté', 'pȟasú', 'pȟayá', 'pȟáza', 'pȟóǧe', 'sipȟá', 'siŋté', 'slála', 'thezí', 'thukí', 'thípi', 'tȟahú', 'tȟaló', 'tȟaté', 'tȟápa', 'tȟóla', 'wagmú', 'wačhí', 'wašíŋ', 'waȟpé', 'wítka', 'yakpí', 'yaŋká', 'yašpá', 'yuksá', 'yukȟé', 'íŋyaŋ', 'óhuta', 'ókaǧa', 'čhečá', 'čhuwí', 'čhápa', 'čháǧa', 'čhéya', 'čhéǧa', 'škáta', 'škáte', 'šásaŋ', 'šúŋka', 'ǧíȟča'],
[79, 'abléza', 'akáȟpe', 'aphíya', 'asáŋpi', 'eháŋni', 'gmigmá', 'gmigmí', 'gnašká', 'hayápi', 'hetȟúŋ', 'heȟáka', 'hiŋháŋ', 'hiŋšmá', 'hotȟúŋ', 'háŋska', 'igmúla', 'iktómi', 'inápȟa', 'iyápȟa', 'ičáške', 'iškáhu', 'kaȟápa', 'kiŋyáŋ', 'ksabyá', 'kuŋkúŋ', 'káǧapi', 'kȟaŋǧí', 'kȟáŋta', 'ločhíŋ', 'maǧážu', 'niséhu', 'nuŋwáŋ', 'okhúže', 'olówaŋ', 'omníča', 'onážiŋ', 'oyáŋke', 'oíyahe', 'oíčazo', 'oȟlóka', 'papsúŋ', 'pteóle', 'pustág', 'pȟeháŋ', 'pȟehíŋ', 'siyéte', 'skaská', 'sloháŋ', 'thičhé', 'tȟáŋka', 'tȟáȟča', 'uŋzóǧe', 'wakáǧa', 'wakȟáŋ', 'wayásu', 'wayáwa', 'waákaŋ', 'waŋblí', 'wápaha', 'wíkȟaŋ', 'wíŋyaŋ', 'wóhela', 'wópazo', 'wótapi', 'wówapi', 'wówaši', 'wóyute', 'yatkáŋ', 'yútapi', 'zuzéča', 'ósmaka', 'čhasmú', 'čhaŋkú', 'čhekpá', 'čhetáŋ', 'čhešká', 'čhoǧíŋ', 'špáŋpi', 'ǧiǧíla'],
[74, 'agléška', 'aígluta', 'aǧúyapi', 'glužáža', 'halháta', 'heyókȟa', 'hignáku', 'hokhúwa', 'hokšíla', 'hoštáka', 'hustóla', 'ikpákpi', 'itókaǧa', 'itówapi', 'itȟókšu', 'iyáyeya', 'ičhósye', 'ištíŋma', 'kisúŋla', 'matúgna', 'maǧáska', 'mniwátu', 'mázaska', 'owáyawa', 'oíȟpeya', 'pagmúpi', 'ptéčela', 'pȟóskil', 'siŋtúpi', 'skúyela', 'spakéli', 'suótala', 'theȟíla', 'thikáǧa', 'thiwáhe', 'thiyópa', 'tȟapȟúŋ', 'tȟaspáŋ', 'tȟawíču', 'tȟašúpa', 'tȟókahu', 'waglúla', 'wagmíza', 'wagmúzi', 'waháŋpi', 'wakhéya', 'wakhúwa', 'walšína', 'wamánuŋ', 'wapȟáte', 'watópȟa', 'wayázaŋ', 'waúŋčha', 'wičháša', 'wábloša', 'wíŋyela', 'wóglaka', 'wóžuthi', 'yukȟápa', 'yutítaŋ', 'yuȟláta', 'yuȟléča', 'zigzíča', 'épatȟaŋ', 'íkačhaŋ', 'íŋyaŋka', 'čhaŋkpé', 'čhaŋpȟá', 'čhaŋšíŋ', 'čheyáka', 'čhiŋkší', 'škátapi', 'šokšóka', 'šuŋǧíla'],
[66, 'akíglake', 'akíčhita', 'apášluta', 'asníkiya', 'glegléǧa', 'gliȟpáya', 'haŋpkȟáŋ', 'hoškéhaŋ', 'héblaska', 'hóšnašna', 'hútȟotȟo', 'iglúziča', 'iglúžaža', 'ináhomni', 'iphíyaka', 'iyúhomni', 'iyúltȟuŋ', 'ičáhomni', 'ištámaza', 'khukhúše', 'kȟoškéku', 'makȟágle', 'makȟóčhe', 'mniwáŋča', 'napíŋkpa', 'napógmus', 'nitéhepi', 'opémnila', 'opémnipi', 'othéȟika', 'owákaȟla', 'oíŋyaŋka', 'psípsiča', 'pȟéstola', 'siŋtéšla', 'subláska', 'tȟablóka', 'tȟažúška', 'wablúška', 'wapásika', 'wapȟápȟa', 'watȟókča', 'watȟótȟo', 'wayázopi', 'waákhiya', 'waŋyáŋka', 'waȟčáȟča', 'wičháȟpi', 'wíhaŋbla', 'wíyukčaŋ', 'wíčhokaŋ', 'wóhitika', 'yaȟúǧapi', 'yukpáŋpi', 'yuȟláȟla', 'ziŋtkála', 'íputȟaka', 'íŋyaŋšlo', 'čhekpápi', 'čhiŋčála', 'čhosyápi', 'čháŋwata', 'čhúŋšoke', 'šaglóǧaŋ', 'šuŋȟpála', 'šúŋšuŋla'],
[63, 'akálapila', 'akáŋhaŋpa', 'akáŋyaŋka', 'asápazila', 'awáŋyaŋka', 'hokšíčala', 'hunáhomni', 'huŋyákȟuŋ', 'igmúgleǧa', 'imáǧaǧaya', 'ithígnila', 'itȟúŋkala', 'iwátȟokšu', 'ištáȟehiŋ', 'kichízapi', 'kičhízapi', 'kȟaŋíyuwi', 'maǧáksiča', 'napókaške', 'niníyaŋpi', 'niǧésaŋla', 'oštéšteka', 'oštéšteya', 'ptegléška', 'pšiŋskúya', 'pšíŋkčeka', 'pȟabláska', 'pȟelkásni', 'skúyeyapi', 'thigmígma', 'thihúȟaka', 'thiyúžaža', 'thuswéčha', 'tȟanáǧila', 'tȟaspáŋzi', 'tȟatéwata', 'tȟatȟáŋka', 'uŋžíŋčala', 'waglékšuŋ', 'wagmúčhaŋ', 'wahíŋheya', 'wakáhiŋta', 'wakíŋyela', 'wakȟáŋgli', 'waníyaŋpi', 'wapȟóštaŋ', 'waskúyeča', 'wawíyuŋpi', 'waátuŋwaŋ', 'waúŋčhala', 'wačhékiye', 'waŋkáyeya', 'wažúšteča', 'witȟáŋšna', 'wičhítowa', 'zugzúkela', 'zíškopela', 'čhapȟúŋka', 'čhaŋháŋpi', 'čhaŋkȟáhu', 'čháŋthipi', 'čhúŋwiŋža', 'špaŋyáŋpi'],
[51, 'aǧúyapiblu', 'haŋkášitku', 'hiŋgnátȟuŋ', 'igmúgleška', 'igmútȟaŋka', 'ištákakpaŋ', 'khiíŋyaŋke', 'makȟáyublu', 'matȟówičhá', 'maštéhaŋpa', 'maštíŋčala', 'mázačhaŋku', 'napȟáhuŋka', 'owáčhekiye', 'peháŋhaŋla', 'phuthíŋhiŋ', 'pȟaŋǧízizi', 'thikáitepa', 'thukíhasaŋ', 'thíŋgleška', 'thíŋpsiŋla', 'tȟabhíŋšma', 'tȟamníoȟpi', 'tȟaspáŋpȟa', 'tȟaspáŋtȟo', 'tȟatȟókala', 'wagmúšatȟo', 'waháčhaŋka', 'waksáksapi', 'wakȟályapi', 'wakȟáŋyeža', 'wapȟáhiŋka', 'watȟápȟela', 'waákisniya', 'waštágyapi', 'waȟúpakoza', 'waȟčálaska', 'wičhíŋčala', 'čhaŋbláska', 'čhaŋkpéška', 'čhaŋkážipa', 'čhaŋyúwipi', 'čhaȟsníyaŋ', 'čheškíkȟaŋ', 'čhiŋkšítku', 'čhuwígnaka', 'čhuwínuŋǧa', 'čhuwíyuksa', 'šičáhowaya', 'šuŋglézela', 'šuŋgmánitu']]
